export const uniLincoln = {
  slug: "uni-lincoln",
  guideId: "study",
  categoryId: "universities",
  titleZh: "林肯大学：专业、校区与世界排名",
  titleEn: "Lincoln University: programmes, campus and world ranking",
  excerptZh: "林肯大学（Lincoln University）位于林肯镇。QS 2026 世界大学排名约 407（新西兰第 7）。官网、校区与适合人群见正文。",
  excerptEn: "Lincoln University is based in Lincoln (near Christchurch). QS World University Rankings 2026: about 407 (NZ #7). Official site, campus and fit notes below.",
  image: "/images/study-feature.jpg",
  imageAltZh: "林肯大学校园与留学资料",
  imageAltEn: "Lincoln University campus and study notes",
  website: "https://www.lincoln.ac.nz/",
  readingMins: 7,
  sectionsZh: [
    {
      type: "links",
      items: [
        { href: "https://www.lincoln.ac.nz/", label: "打开 林肯大学 官网" },
        { href: "https://www.topuniversities.com/world-university-rankings", label: "打开 QS 世界大学排名官网" },
      ],
    },
    {
      type: "articleLinks",
      items: [
        { slug: "nz-eight-universities", label: "返回：新西兰八大公立对照" },
        { slug: "uni-auckland", label: "对照：奥克兰大学" },
        { slug: "uni-otago", label: "对照：奥塔哥大学" },
        { slug: "uni-massey", label: "对照：梅西大学" },
      ],
    },
    { type: "h2", text: "学校定位" },
    { type: "p", text: "林肯大学（Lincoln University）是新西兰八大公立大学之一。主校区/主要学习地点：林肯镇（Lincoln，基督城附近）。新西兰规模较小、特色鲜明的公立大学，农学、环境与土地相关领域是核心叙事。综合 QS 排名低于综合型八大，但专业匹配往往更重要。" },
    {
      type: "table",
      caption: "快速对照（排名为 QS 约数，会每年更新）",
      headers: ["项目", "信息"],
      rows: [
        ["中文常用名", "林肯大学"],
        ["英文正式名", "Lincoln University"],
        ["城市/校区", "林肯镇（Lincoln，基督城附近）"],
        ["QS 2026 世界排名", "407"],
        ["QS 2025 世界排名", "=371"],
        ["新西兰境内大致位次", "第 7"],
        ["官网", "https://www.lincoln.ac.nz/"],
      ],
    },
    { type: "h2", text: "更适合谁" },
    { type: "p", text: "明确农学、环境、土地、食品供应链等方向的人；不适合只看综合排名选校的人。" },
    { type: "ul", items: [
      "农学/环境专科定位清晰",
      "靠近基督城，可兼顾南岛生活",
      "国际师生比例等指标常被提及",
      "先定专业方向，再看该校该专业是否开放国际生、学位层级与英文要求。",
      "把学费 invoice 与当地房租、交通放进 12 个月预算。",
    ]},
    { type: "p", text: "小镇校园社交圈更小；确认住宿、通勤基督城与实习/实地课安排。" },
    { type: "tip", title: "关于世界排名", text: "本文 QS 数字来自公开报道的 2026/2025 World University Rankings 结果，仅作选校参考。不同榜单（QS、THE、ARWU）算法不同，专业排名与综合排名也可能不一致。申请前以 QS 官网当年榜单与大学官网为准。" },
    { type: "h2", text: "申请前核实清单" },
    { type: "steps", items: [
      { title: "打开官网课程页", text: "在 https://www.lincoln.ac.nz/ 核对专业名称、入学要求、学费与开学时间。" },
      { title: "核对英文与学术条件", text: "确认 IELTS/PTE 等总分与单项、学历背景与是否接受 pathway。" },
      { title: "对照生活成本", text: "把学费、保险、房租与交通放进 12 个月预算；奥克兰与地方城市差一截。" },
      { title: "再看排名是否匹配目标", text: "若目标是某专业就业或移民路径，专业匹配往往比综合排名数字更重要。" },
    ]},
  ],
  sectionsEn: [
    {
      type: "links",
      items: [
        { href: "https://www.lincoln.ac.nz/", label: "Open Lincoln University website" },
        { href: "https://www.topuniversities.com/world-university-rankings", label: "Open QS World University Rankings" },
      ],
    },
    {
      type: "articleLinks",
      items: [
        { slug: "nz-eight-universities", label: "Back: NZ eight universities overview" },
        { slug: "uni-auckland", label: "Compare: The University of Auckland" },
        { slug: "uni-otago", label: "Compare: University of Otago" },
        { slug: "uni-massey", label: "Compare: Massey University" },
      ],
    },
    { type: "h2", text: "Positioning" },
    { type: "p", text: "Lincoln University is one of New Zealand’s eight public universities. Main location: Lincoln (near Christchurch). A smaller, specialised public university; agriculture, environment and land-related fields are the core story. Overall QS sits below larger comprehensives—subject fit usually matters more." },
    {
      type: "table",
      caption: "Quick facts (QS ranks are approximate and update yearly)",
      headers: ["Item", "Detail"],
      rows: [
        ["Common Chinese name", "林肯大学"],
        ["Official English name", "Lincoln University"],
        ["City / campuses", "Lincoln (near Christchurch)"],
        ["QS 2026 world rank", "407"],
        ["QS 2025 world rank", "=371"],
        ["Approx. NZ order", "#7"],
        ["Official website", "https://www.lincoln.ac.nz/"],
      ],
    },
    { type: "h2", text: "Who it suits" },
    { type: "p", text: "Students clear on agriculture, environment, land or food-supply pathways—not those choosing only by overall rank." },
    { type: "ul", items: [
      "Clear agriculture/environment specialisation",
      "Near Christchurch for South Island living",
      "International student/staff metrics often noted",
      "Confirm the major first, then entry requirements, degree level and English scores.",
      "Put tuition invoices plus local rent and transport into a 12-month budget.",
    ]},
    { type: "p", text: "Smaller town campus and social circle—confirm housing, Christchurch commute and fieldwork/internship plans." },
    { type: "tip", title: "About world rankings", text: "QS figures here reflect publicly reported 2026/2025 World University Rankings results and are for orientation only. QS, THE and ARWU use different methods; subject ranks can differ from overall ranks. Verify on QS and the university website before applying." },
    { type: "h2", text: "Pre-application checklist" },
    { type: "steps", items: [
      { title: "Open the official programme page", text: "On https://www.lincoln.ac.nz/, confirm programme name, entry rules, fees and start dates." },
      { title: "Check English and academic entry", text: "Confirm IELTS/PTE totals and bands, prior study and any pathway options." },
      { title: "Compare living costs", text: "Budget tuition, insurance, rent and transport for 12 months; Auckland differs from regional cities." },
      { title: "Decide if the rank matches your goal", text: "For employment or migration pathways, subject fit often matters more than the overall number." },
    ]},
  ],
};
