export const uniMassey = {
  slug: "uni-massey",
  guideId: "study",
  categoryId: "universities",
  titleZh: "梅西大学：专业、校区与世界排名",
  titleEn: "Massey University: programmes, campus and world ranking",
  excerptZh: "梅西大学（Massey University）位于奥克兰、帕默斯顿北。QS 2026 世界大学排名约 =230（新西兰第 3）。官网、校区与适合人群见正文。",
  excerptEn: "Massey University is based in Auckland, Palmerston North and Wellington campuses. QS World University Rankings 2026: about =230 (NZ #3). Official site, campus and fit notes below.",
  image: "/images/study-feature.jpg",
  imageAltZh: "梅西大学校园与留学资料",
  imageAltEn: "Massey University campus and study notes",
  website: "https://www.massey.ac.nz/",
  readingMins: 7,
  sectionsZh: [
    {
      type: "links",
      items: [
        { href: "https://www.massey.ac.nz/", label: "打开 梅西大学 官网" },
        { href: "https://www.topuniversities.com/world-university-rankings", label: "打开 QS 世界大学排名官网" },
      ],
    },
    {
      type: "articleLinks",
      items: [
        { slug: "nz-eight-universities", label: "返回：新西兰八大公立对照" },
        { slug: "uni-auckland", label: "对照：奥克兰大学" },
        { slug: "uni-otago", label: "对照：奥塔哥大学" },
        { slug: "uni-victoria", label: "对照：惠灵顿维多利亚大学" },
      ],
    },
    { type: "h2", text: "学校定位" },
    { type: "p", text: "梅西大学（Massey University）是新西兰八大公立大学之一。主校区/主要学习地点：奥克兰、帕默斯顿北（Palmerston North）、惠灵顿多校区。多校区公立大学，农学与兽医相关领域常被单独提及；也可在奥克兰/惠灵顿校区读部分课程。申请时务必看清专业开在哪个校区。" },
    {
      type: "table",
      caption: "快速对照（排名为 QS 约数，会每年更新）",
      headers: ["项目", "信息"],
      rows: [
        ["中文常用名", "梅西大学"],
        ["英文正式名", "Massey University"],
        ["城市/校区", "奥克兰、帕默斯顿北（Palmerston North）、惠灵顿多校区"],
        ["QS 2026 世界排名", "=230"],
        ["QS 2025 世界排名", "=239"],
        ["新西兰境内大致位次", "第 3"],
        ["官网", "https://www.massey.ac.nz/"],
      ],
    },
    { type: "h2", text: "更适合谁" },
    { type: "p", text: "需要多校区选择，或对农学、兽医、创意、商科应用路径感兴趣的人。" },
    { type: "ul", items: [
      "校区选择灵活",
      "农学/兽医等特色方向",
      "可兼顾大都市与地方城市生活",
      "先定专业方向，再看该校该专业是否开放国际生、学位层级与英文要求。",
      "把学费 invoice 与当地房租、交通放进 12 个月预算。",
    ]},
    { type: "p", text: "同一学校不同校区，生活费与兼职环境差很多；短名单里要写清「专业 + 校区」。" },
    { type: "tip", title: "关于世界排名", text: "本文 QS 数字来自公开报道的 2026/2025 World University Rankings 结果，仅作选校参考。不同榜单（QS、THE、ARWU）算法不同，专业排名与综合排名也可能不一致。申请前以 QS 官网当年榜单与大学官网为准。" },
    { type: "h2", text: "申请前核实清单" },
    { type: "steps", items: [
      { title: "打开官网课程页", text: "在 https://www.massey.ac.nz/ 核对专业名称、入学要求、学费与开学时间。" },
      { title: "核对英文与学术条件", text: "确认 IELTS/PTE 等总分与单项、学历背景与是否接受 pathway。" },
      { title: "对照生活成本", text: "把学费、保险、房租与交通放进 12 个月预算；奥克兰与地方城市差一截。" },
      { title: "再看排名是否匹配目标", text: "若目标是某专业就业或移民路径，专业匹配往往比综合排名数字更重要。" },
    ]},
  ],
  sectionsEn: [
    {
      type: "links",
      items: [
        { href: "https://www.massey.ac.nz/", label: "Open Massey University website" },
        { href: "https://www.topuniversities.com/world-university-rankings", label: "Open QS World University Rankings" },
      ],
    },
    {
      type: "articleLinks",
      items: [
        { slug: "nz-eight-universities", label: "Back: NZ eight universities overview" },
        { slug: "uni-auckland", label: "Compare: The University of Auckland" },
        { slug: "uni-otago", label: "Compare: University of Otago" },
        { slug: "uni-victoria", label: "Compare: Victoria University of Wellington" },
      ],
    },
    { type: "h2", text: "Positioning" },
    { type: "p", text: "Massey University is one of New Zealand’s eight public universities. Main location: Auckland, Palmerston North and Wellington campuses. A multi-campus public university; agriculture and veterinary fields are often highlighted. Some programmes run in Auckland or Wellington—always check which campus hosts your major." },
    {
      type: "table",
      caption: "Quick facts (QS ranks are approximate and update yearly)",
      headers: ["Item", "Detail"],
      rows: [
        ["Common Chinese name", "梅西大学"],
        ["Official English name", "Massey University"],
        ["City / campuses", "Auckland, Palmerston North and Wellington campuses"],
        ["QS 2026 world rank", "=230"],
        ["QS 2025 world rank", "=239"],
        ["Approx. NZ order", "#3"],
        ["Official website", "https://www.massey.ac.nz/"],
      ],
    },
    { type: "h2", text: "Who it suits" },
    { type: "p", text: "Students who want multi-campus options or interest in agriculture, veterinary, creative or applied business paths." },
    { type: "ul", items: [
      "Flexible campus choices",
      "Distinctive agriculture/veterinary strengths",
      "Can balance big-city and regional living",
      "Confirm the major first, then entry requirements, degree level and English scores.",
      "Put tuition invoices plus local rent and transport into a 12-month budget.",
    ]},
    { type: "p", text: "Living costs and part-time work differ a lot by campus—shortlist as “programme + campus”." },
    { type: "tip", title: "About world rankings", text: "QS figures here reflect publicly reported 2026/2025 World University Rankings results and are for orientation only. QS, THE and ARWU use different methods; subject ranks can differ from overall ranks. Verify on QS and the university website before applying." },
    { type: "h2", text: "Pre-application checklist" },
    { type: "steps", items: [
      { title: "Open the official programme page", text: "On https://www.massey.ac.nz/, confirm programme name, entry rules, fees and start dates." },
      { title: "Check English and academic entry", text: "Confirm IELTS/PTE totals and bands, prior study and any pathway options." },
      { title: "Compare living costs", text: "Budget tuition, insurance, rent and transport for 12 months; Auckland differs from regional cities." },
      { title: "Decide if the rank matches your goal", text: "For employment or migration pathways, subject fit often matters more than the overall number." },
    ]},
  ],
};
