export const uniWaikato = {
  slug: "uni-waikato",
  guideId: "study",
  categoryId: "universities",
  titleZh: "怀卡托大学：专业、校区与世界排名",
  titleEn: "University of Waikato: programmes, campus and world ranking",
  excerptZh: "怀卡托大学（University of Waikato）位于汉密尔顿。QS 2026 世界大学排名约 =281（新西兰第 6）。官网、校区与适合人群见正文。",
  excerptEn: "University of Waikato is based in Hamilton. QS World University Rankings 2026: about =281 (NZ #6). Official site, campus and fit notes below.",
  image: "/images/study-feature.jpg",
  imageAltZh: "怀卡托大学校园与留学资料",
  imageAltEn: "University of Waikato campus and study notes",
  website: "https://www.waikato.ac.nz/",
  readingMins: 7,
  sectionsZh: [
    {
      type: "links",
      items: [
        { href: "https://www.waikato.ac.nz/", label: "打开 怀卡托大学 官网" },
        { href: "https://www.topuniversities.com/world-university-rankings", label: "打开 QS 世界大学排名官网" },
      ],
    },
    {
      type: "articleLinks",
      items: [
        { slug: "nz-eight-universities", label: "返回：新西兰八大公立对照" },
        { slug: "uni-auckland", label: "对照：奥克兰大学" },
        { slug: "uni-otago", label: "对照：奥塔哥大学" },
        { slug: "uni-massey", label: "对照：梅西大学" },
      ],
    },
    { type: "h2", text: "学校定位" },
    { type: "p", text: "怀卡托大学（University of Waikato）是新西兰八大公立大学之一。主校区/主要学习地点：汉密尔顿（Hamilton）；部分课程/校区安排可能涉及陶朗加等地。汉密尔顿主校区，距离奥克兰约 1.5–2 小时车程；综合大学，校园与地方城市生活节奏更缓。QS 位次近年有波动，选校仍以专业与预算为主。" },
    {
      type: "table",
      caption: "快速对照（排名为 QS 约数，会每年更新）",
      headers: ["项目", "信息"],
      rows: [
        ["中文常用名", "怀卡托大学"],
        ["英文正式名", "University of Waikato"],
        ["城市/校区", "汉密尔顿（Hamilton）；部分课程/校区安排可能涉及陶朗加等地"],
        ["QS 2026 世界排名", "=281"],
        ["QS 2025 世界排名", "235"],
        ["新西兰境内大致位次", "第 6"],
        ["官网", "https://www.waikato.ac.nz/"],
      ],
    },
    { type: "h2", text: "更适合谁" },
    { type: "p", text: "希望北岛非奥克兰城市生活，对教育、商科、计算机或环境相关方向感兴趣的人。" },
    { type: "ul", items: [
      "北岛地方城市成本与节奏",
      "到奥克兰仍相对方便",
      "教育/商科/IT 等常见比较项",
      "先定专业方向，再看该校该专业是否开放国际生、学位层级与英文要求。",
      "把学费 invoice 与当地房租、交通放进 12 个月预算。",
    ]},
    { type: "p", text: "兼职市场不如奥克兰密集；若依赖兼职收入，提前看 Seek/Trade Me 当地岗位量。" },
    { type: "tip", title: "关于世界排名", text: "本文 QS 数字来自公开报道的 2026/2025 World University Rankings 结果，仅作选校参考。不同榜单（QS、THE、ARWU）算法不同，专业排名与综合排名也可能不一致。申请前以 QS 官网当年榜单与大学官网为准。" },
    { type: "h2", text: "申请前核实清单" },
    { type: "steps", items: [
      { title: "打开官网课程页", text: "在 https://www.waikato.ac.nz/ 核对专业名称、入学要求、学费与开学时间。" },
      { title: "核对英文与学术条件", text: "确认 IELTS/PTE 等总分与单项、学历背景与是否接受 pathway。" },
      { title: "对照生活成本", text: "把学费、保险、房租与交通放进 12 个月预算；奥克兰与地方城市差一截。" },
      { title: "再看排名是否匹配目标", text: "若目标是某专业就业或移民路径，专业匹配往往比综合排名数字更重要。" },
    ]},
  ],
  sectionsEn: [
    {
      type: "links",
      items: [
        { href: "https://www.waikato.ac.nz/", label: "Open University of Waikato website" },
        { href: "https://www.topuniversities.com/world-university-rankings", label: "Open QS World University Rankings" },
      ],
    },
    {
      type: "articleLinks",
      items: [
        { slug: "nz-eight-universities", label: "Back: NZ eight universities overview" },
        { slug: "uni-auckland", label: "Compare: The University of Auckland" },
        { slug: "uni-otago", label: "Compare: University of Otago" },
        { slug: "uni-massey", label: "Compare: Massey University" },
      ],
    },
    { type: "h2", text: "Positioning" },
    { type: "p", text: "University of Waikato is one of New Zealand’s eight public universities. Main location: Hamilton; some arrangements may involve Tauranga and other locations. Main campus in Hamilton, about 1.5–2 hours from Auckland; a comprehensive university with a calmer regional pace. QS rank has moved recently—prioritise programme fit and budget." },
    {
      type: "table",
      caption: "Quick facts (QS ranks are approximate and update yearly)",
      headers: ["Item", "Detail"],
      rows: [
        ["Common Chinese name", "怀卡托大学"],
        ["Official English name", "University of Waikato"],
        ["City / campuses", "Hamilton; some arrangements may involve Tauranga and other locations"],
        ["QS 2026 world rank", "=281"],
        ["QS 2025 world rank", "235"],
        ["Approx. NZ order", "#6"],
        ["Official website", "https://www.waikato.ac.nz/"],
      ],
    },
    { type: "h2", text: "Who it suits" },
    { type: "p", text: "Students wanting North Island life outside Auckland, with interest in education, business, computing or environment-related fields." },
    { type: "ul", items: [
      "Regional North Island costs and pace",
      "Still relatively accessible to Auckland",
      "Education, business and IT often compared",
      "Confirm the major first, then entry requirements, degree level and English scores.",
      "Put tuition invoices plus local rent and transport into a 12-month budget.",
    ]},
    { type: "p", text: "Part-time work is less dense than Auckland—check Seek/Trade Me local volume if you rely on wages." },
    { type: "tip", title: "About world rankings", text: "QS figures here reflect publicly reported 2026/2025 World University Rankings results and are for orientation only. QS, THE and ARWU use different methods; subject ranks can differ from overall ranks. Verify on QS and the university website before applying." },
    { type: "h2", text: "Pre-application checklist" },
    { type: "steps", items: [
      { title: "Open the official programme page", text: "On https://www.waikato.ac.nz/, confirm programme name, entry rules, fees and start dates." },
      { title: "Check English and academic entry", text: "Confirm IELTS/PTE totals and bands, prior study and any pathway options." },
      { title: "Compare living costs", text: "Budget tuition, insurance, rent and transport for 12 months; Auckland differs from regional cities." },
      { title: "Decide if the rank matches your goal", text: "For employment or migration pathways, subject fit often matters more than the overall number." },
    ]},
  ],
};
