export const uniAut = {
  slug: "uni-aut",
  guideId: "study",
  categoryId: "universities",
  titleZh: "奥克兰理工大学 AUT：专业、校区与世界排名",
  titleEn: "Auckland University of Technology (AUT): programmes, campus and world ranking",
  excerptZh: "奥克兰理工大学 AUT（Auckland University of Technology (AUT)）位于奥克兰。QS 2026 世界大学排名约 =410（新西兰第 8）。官网、校区与适合人群见正文。",
  excerptEn: "Auckland University of Technology (AUT) is based in Auckland (multiple campuses. QS World University Rankings 2026: about =410 (NZ #8). Official site, campus and fit notes below.",
  image: "/images/study-feature.jpg",
  imageAltZh: "奥克兰理工大学 AUT校园与留学资料",
  imageAltEn: "Auckland University of Technology (AUT) campus and study notes",
  website: "https://www.aut.ac.nz/",
  readingMins: 7,
  sectionsZh: [
    {
      type: "links",
      items: [
        { href: "https://www.aut.ac.nz/", label: "打开 奥克兰理工大学 AUT 官网" },
        { href: "https://www.topuniversities.com/world-university-rankings", label: "打开 QS 世界大学排名官网" },
      ],
    },
    {
      type: "articleLinks",
      items: [
        { slug: "nz-eight-universities", label: "返回：新西兰八大公立对照" },
        { slug: "uni-auckland", label: "对照：奥克兰大学" },
        { slug: "uni-otago", label: "对照：奥塔哥大学" },
        { slug: "uni-massey", label: "对照：梅西大学" },
      ],
    },
    { type: "h2", text: "学校定位" },
    { type: "p", text: "奥克兰理工大学 AUT（Auckland University of Technology (AUT)）是新西兰八大公立大学之一。主校区/主要学习地点：奥克兰（多校区，市中心相关校区常见）。八大中偏应用与产业连接的一所；健康、传播、设计、商科与酒店等相关路径常被讨论。综合 QS 低于奥大，但「能不能就业导向学」是另一套问题。" },
    {
      type: "table",
      caption: "快速对照（排名为 QS 约数，会每年更新）",
      headers: ["项目", "信息"],
      rows: [
        ["中文常用名", "奥克兰理工大学 AUT"],
        ["英文正式名", "Auckland University of Technology (AUT)"],
        ["城市/校区", "奥克兰（多校区，市中心相关校区常见）"],
        ["QS 2026 世界排名", "=410"],
        ["QS 2025 世界排名", "412"],
        ["新西兰境内大致位次", "第 8"],
        ["官网", "https://www.aut.ac.nz/"],
      ],
    },
    { type: "h2", text: "更适合谁" },
    { type: "p", text: "偏好应用型、就业导向课程，想在奥克兰读书但不一定冲综合排名第一的人。" },
    { type: "ul", items: [
      "应用与实习导向叙事强",
      "奥克兰区位便于兼职与项目",
      "课程结构常更贴近实务",
      "先定专业方向，再看该校该专业是否开放国际生、学位层级与英文要求。",
      "把学费 invoice 与当地房租、交通放进 12 个月预算。",
    ]},
    { type: "p", text: "与奥克兰大学不是同一所；短名单里写全称 AUT / Auckland University of Technology，避免和 UoA 混淆。" },
    { type: "tip", title: "关于世界排名", text: "本文 QS 数字来自公开报道的 2026/2025 World University Rankings 结果，仅作选校参考。不同榜单（QS、THE、ARWU）算法不同，专业排名与综合排名也可能不一致。申请前以 QS 官网当年榜单与大学官网为准。" },
    { type: "h2", text: "申请前核实清单" },
    { type: "steps", items: [
      { title: "打开官网课程页", text: "在 https://www.aut.ac.nz/ 核对专业名称、入学要求、学费与开学时间。" },
      { title: "核对英文与学术条件", text: "确认 IELTS/PTE 等总分与单项、学历背景与是否接受 pathway。" },
      { title: "对照生活成本", text: "把学费、保险、房租与交通放进 12 个月预算；奥克兰与地方城市差一截。" },
      { title: "再看排名是否匹配目标", text: "若目标是某专业就业或移民路径，专业匹配往往比综合排名数字更重要。" },
    ]},
  ],
  sectionsEn: [
    {
      type: "links",
      items: [
        { href: "https://www.aut.ac.nz/", label: "Open Auckland University of Technology (AUT) website" },
        { href: "https://www.topuniversities.com/world-university-rankings", label: "Open QS World University Rankings" },
      ],
    },
    {
      type: "articleLinks",
      items: [
        { slug: "nz-eight-universities", label: "Back: NZ eight universities overview" },
        { slug: "uni-auckland", label: "Compare: The University of Auckland" },
        { slug: "uni-otago", label: "Compare: University of Otago" },
        { slug: "uni-massey", label: "Compare: Massey University" },
      ],
    },
    { type: "h2", text: "Positioning" },
    { type: "p", text: "Auckland University of Technology (AUT) is one of New Zealand’s eight public universities. Main location: Auckland (multiple campuses; city-centre locations common). Among the eight, more applied and industry-linked; health, communication, design, business and hospitality paths are often discussed. Overall QS sits below Auckland—but “career-focused learning” is a different question." },
    {
      type: "table",
      caption: "Quick facts (QS ranks are approximate and update yearly)",
      headers: ["Item", "Detail"],
      rows: [
        ["Common Chinese name", "奥克兰理工大学 AUT"],
        ["Official English name", "Auckland University of Technology (AUT)"],
        ["City / campuses", "Auckland (multiple campuses; city-centre locations common)"],
        ["QS 2026 world rank", "=410"],
        ["QS 2025 world rank", "412"],
        ["Approx. NZ order", "#8"],
        ["Official website", "https://www.aut.ac.nz/"],
      ],
    },
    { type: "h2", text: "Who it suits" },
    { type: "p", text: "Students who prefer applied, career-focused study in Auckland without needing the top overall rank." },
    { type: "ul", items: [
      "Strong applied/internship narrative",
      "Auckland location helps part-time work and projects",
      "Programme structures often more practice-oriented",
      "Confirm the major first, then entry requirements, degree level and English scores.",
      "Put tuition invoices plus local rent and transport into a 12-month budget.",
    ]},
    { type: "p", text: "Not the same as the University of Auckland—use full name AUT to avoid mixing with UoA." },
    { type: "tip", title: "About world rankings", text: "QS figures here reflect publicly reported 2026/2025 World University Rankings results and are for orientation only. QS, THE and ARWU use different methods; subject ranks can differ from overall ranks. Verify on QS and the university website before applying." },
    { type: "h2", text: "Pre-application checklist" },
    { type: "steps", items: [
      { title: "Open the official programme page", text: "On https://www.aut.ac.nz/, confirm programme name, entry rules, fees and start dates." },
      { title: "Check English and academic entry", text: "Confirm IELTS/PTE totals and bands, prior study and any pathway options." },
      { title: "Compare living costs", text: "Budget tuition, insurance, rent and transport for 12 months; Auckland differs from regional cities." },
      { title: "Decide if the rank matches your goal", text: "For employment or migration pathways, subject fit often matters more than the overall number." },
    ]},
  ],
};
