export const uniOtago = {
  slug: "uni-otago",
  guideId: "study",
  categoryId: "universities",
  titleZh: "奥塔哥大学：专业、校区与世界排名",
  titleEn: "University of Otago: programmes, campus and world ranking",
  excerptZh: "奥塔哥大学（University of Otago）位于达尼丁。QS 2026 世界大学排名约 =197（新西兰第 2）。官网、校区与适合人群见正文。",
  excerptEn: "University of Otago is based in Dunedin. QS World University Rankings 2026: about =197 (NZ #2). Official site, campus and fit notes below.",
  image: "/images/study-feature.jpg",
  imageAltZh: "奥塔哥大学校园与留学资料",
  imageAltEn: "University of Otago campus and study notes",
  website: "https://www.otago.ac.nz/",
  readingMins: 7,
  sectionsZh: [
    {
      type: "links",
      items: [
        { href: "https://www.otago.ac.nz/", label: "打开 奥塔哥大学 官网" },
        { href: "https://www.topuniversities.com/world-university-rankings", label: "打开 QS 世界大学排名官网" },
      ],
    },
    {
      type: "articleLinks",
      items: [
        { slug: "nz-eight-universities", label: "返回：新西兰八大公立对照" },
        { slug: "uni-auckland", label: "对照：奥克兰大学" },
        { slug: "uni-massey", label: "对照：梅西大学" },
        { slug: "uni-victoria", label: "对照：惠灵顿维多利亚大学" },
      ],
    },
    { type: "h2", text: "学校定位" },
    { type: "p", text: "奥塔哥大学（University of Otago）是新西兰八大公立大学之一。主校区/主要学习地点：达尼丁（Dunedin）；健康科学等专业也有其他校区安排。新西兰历史最悠久的大学之一，达尼丁校园氛围浓；健康科学、生命科学与人文社科口碑突出。QS 2026 回到世界前 200。" },
    {
      type: "table",
      caption: "快速对照（排名为 QS 约数，会每年更新）",
      headers: ["项目", "信息"],
      rows: [
        ["中文常用名", "奥塔哥大学"],
        ["英文正式名", "University of Otago"],
        ["城市/校区", "达尼丁（Dunedin）；健康科学等专业也有其他校区安排"],
        ["QS 2026 世界排名", "=197"],
        ["QS 2025 世界排名", "214"],
        ["新西兰境内大致位次", "第 2"],
        ["官网", "https://www.otago.ac.nz/"],
      ],
    },
    { type: "h2", text: "更适合谁" },
    { type: "p", text: "偏好校园生活感、健康科学/生命科学方向，或想避开奥克兰高生活成本的人。" },
    { type: "ul", items: [
      "校园社区感强，适合沉浸式留学",
      "健康与生命科学方向常见于短名单",
      "生活成本通常低于奥克兰",
      "先定专业方向，再看该校该专业是否开放国际生、学位层级与英文要求。",
      "把学费 invoice 与当地房租、交通放进 12 个月预算。",
    ]},
    { type: "p", text: "达尼丁偏南、冬季偏冷；交通与兼职机会和奥克兰不同，落地前先看住宿与通勤。" },
    { type: "tip", title: "关于世界排名", text: "本文 QS 数字来自公开报道的 2026/2025 World University Rankings 结果，仅作选校参考。不同榜单（QS、THE、ARWU）算法不同，专业排名与综合排名也可能不一致。申请前以 QS 官网当年榜单与大学官网为准。" },
    { type: "h2", text: "申请前核实清单" },
    { type: "steps", items: [
      { title: "打开官网课程页", text: "在 https://www.otago.ac.nz/ 核对专业名称、入学要求、学费与开学时间。" },
      { title: "核对英文与学术条件", text: "确认 IELTS/PTE 等总分与单项、学历背景与是否接受 pathway。" },
      { title: "对照生活成本", text: "把学费、保险、房租与交通放进 12 个月预算；奥克兰与地方城市差一截。" },
      { title: "再看排名是否匹配目标", text: "若目标是某专业就业或移民路径，专业匹配往往比综合排名数字更重要。" },
    ]},
  ],
  sectionsEn: [
    {
      type: "links",
      items: [
        { href: "https://www.otago.ac.nz/", label: "Open University of Otago website" },
        { href: "https://www.topuniversities.com/world-university-rankings", label: "Open QS World University Rankings" },
      ],
    },
    {
      type: "articleLinks",
      items: [
        { slug: "nz-eight-universities", label: "Back: NZ eight universities overview" },
        { slug: "uni-auckland", label: "Compare: The University of Auckland" },
        { slug: "uni-massey", label: "Compare: Massey University" },
        { slug: "uni-victoria", label: "Compare: Victoria University of Wellington" },
      ],
    },
    { type: "h2", text: "Positioning" },
    { type: "p", text: "University of Otago is one of New Zealand’s eight public universities. Main location: Dunedin; some health-science arrangements elsewhere. One of NZ’s oldest universities with a strong Dunedin campus culture; well regarded in health, life sciences and humanities. QS 2026 returns to the global top 200." },
    {
      type: "table",
      caption: "Quick facts (QS ranks are approximate and update yearly)",
      headers: ["Item", "Detail"],
      rows: [
        ["Common Chinese name", "奥塔哥大学"],
        ["Official English name", "University of Otago"],
        ["City / campuses", "Dunedin; some health-science arrangements elsewhere"],
        ["QS 2026 world rank", "=197"],
        ["QS 2025 world rank", "214"],
        ["Approx. NZ order", "#2"],
        ["Official website", "https://www.otago.ac.nz/"],
      ],
    },
    { type: "h2", text: "Who it suits" },
    { type: "p", text: "Students who want a campus-town feel, health/life sciences focus, or lower living costs than Auckland." },
    { type: "ul", items: [
      "Strong campus community for immersive study abroad",
      "Health and life sciences often on shortlists",
      "Living costs usually lower than Auckland",
      "Confirm the major first, then entry requirements, degree level and English scores.",
      "Put tuition invoices plus local rent and transport into a 12-month budget.",
    ]},
    { type: "p", text: "Dunedin is further south and cooler in winter; transport and part-time work differ from Auckland—plan housing and commute early." },
    { type: "tip", title: "About world rankings", text: "QS figures here reflect publicly reported 2026/2025 World University Rankings results and are for orientation only. QS, THE and ARWU use different methods; subject ranks can differ from overall ranks. Verify on QS and the university website before applying." },
    { type: "h2", text: "Pre-application checklist" },
    { type: "steps", items: [
      { title: "Open the official programme page", text: "On https://www.otago.ac.nz/, confirm programme name, entry rules, fees and start dates." },
      { title: "Check English and academic entry", text: "Confirm IELTS/PTE totals and bands, prior study and any pathway options." },
      { title: "Compare living costs", text: "Budget tuition, insurance, rent and transport for 12 months; Auckland differs from regional cities." },
      { title: "Decide if the rank matches your goal", text: "For employment or migration pathways, subject fit often matters more than the overall number." },
    ]},
  ],
};
