/** Auto-generated by scripts/write-expanded-articles.mjs — edit that script, then re-run. */

export const articles = [
  {
    "slug": "pte-private-schools",
    "guideId": "study",
    "titleZh": "AIS / ICL / Yoobee / NZSE / Future Skills：学费与怎么选",
    "titleEn": "AIS, ICL, Yoobee, NZSE, Future Skills: fees and who they suit",
    "excerptZh": "私立与技能学校常见短名单：城市、专业方向、大致学费（纽币）与适合谁——费用以官网为准。",
    "excerptEn": "A practical private/skills shortlist: city, typical programmes, approximate NZD fees, and who each suits—verify on official sites.",
    "image": "/images/study-feature.png",
    "imageAltZh": "新西兰私立学院与技能学校",
    "imageAltEn": "A New Zealand private college campus",
    "bodyZh": [
      "先说清楚：本文不是八大/大学排名清单，而是很多中国学生实际会问的私立培训机构（PTE）与技能/应用型学院路径。学费会随学年、专业、奖学金与地区促销变动；下列数字为近年公开材料中的大致区间（纽币 NZD），报名前务必核对官网。",
      {
        "type": "h2",
        "text": "怎么快速筛学校"
      },
      "建议按五步筛：① NZQA 级别与课程时长（证书/文凭/本科/研文/硕士差很大）；② 英语是 IELTS、PTE Academic 还是 NZCEL/语言班；③ 专业是否匹配目标；④ 奥克兰房租会显著拉高总成本；⑤ 别把「好录取」当成「好就业」或「好移民」。",
      "本指南为每所学校准备了独立详解。下面先做总览对照，再点进各校专文看课程、学费与适合人群。",
      {
        "type": "image",
        "src": "/images/article-campus-class.png",
        "alt": "课堂学习场景",
        "caption": "应用型学院更强调小班与实务训练，选校时同时看级别与城市生活成本。"
      },
      {
        "type": "h2",
        "text": "五所学校一览"
      },
      "AIS——奥克兰，应用型商科/IT/酒店与语言衔接；文凭/研文常见约 NZD 22,000–27,000，本科约 NZD 22,000–24,000/年，部分硕士约 NZD 40,000 量级。官网 https://ais.ac.nz/",
      "ICL——奥克兰 CBD 商学院路径（站长就读）；Level 5 到 Level 9 国际生常见约 NZD 23,000–48,500，另有报名与材料费，促销价以 Offer 为准。官网 https://icl.ac.nz/",
      "Yoobee——创意与数字（动画、设计、软件）；文凭/本科常见约 NZD 27,300，另收资源/行政费。官网 https://yoobee.ac.nz/",
      "NZSE / NZSEG——技能就业导向（IT、商务、数据分析、教学等）；不同课差价大，约 NZD 18,900–35,500+。若见「NESEG」多半是 NZSEG 误写。官网 https://nzse.ac.nz/",
      "Future Skills——奥克兰 Queen Street；应用管理/建筑相关与部分硕士；标价例约 NZD 23,900–40,500，常有奖学金后净价。官网 https://www.futureskills.co.nz/",
      {
        "type": "image",
        "src": "/images/article-auckland-cbd.png",
        "alt": "奥克兰市中心街景",
        "caption": "ICL、Future Skills 等路径多在奥克兰 CBD，通勤方便但房租通常更高。"
      },
      {
        "type": "h2",
        "text": "专业怎么对号"
      },
      "商科/管理 → ICL、AIS、Future Skills、NZSE；IT/软件 → Yoobee、AIS、NZSE、Future Skills；酒店旅游 → AIS、ICL；创意动画 → Yoobee。",
      "做短名单时建议「1 所主申 + 1 所备选」，并把学费标价、促销价、材料费、一年房租写进同一张表。需要按背景压缩名单时，可用首页咨询表整理信息。"
    ],
    "bodyEn": [
      "This is not an “eight universities” list. It covers PTE/skills providers many Chinese students actually ask about. Fees change by year, programme and promo—figures are approximate NZD; verify on official sites.",
      {
        "type": "h2",
        "text": "How to filter quickly"
      },
      "Check NZQA level and length, English pathway, subject fit, Auckland rent, and realistic outcomes—not just easy entry.",
      "Each school has its own deep-dive article. Use this page as a comparison hub, then open the dedicated guides.",
      {
        "type": "image",
        "src": "/images/article-campus-class.png",
        "alt": "Classroom study scene",
        "caption": "Applied colleges often emphasise smaller classes and practical training—compare level and city living costs together."
      },
      {
        "type": "h2",
        "text": "Five-school snapshot"
      },
      "AIS—Auckland applied business/IT/hospitality with language bridging; diplomas/PGDips often ~NZD 22k–27k, bachelor ~NZD 22k–24k/year, some master’s ~NZD 40k. https://ais.ac.nz/",
      "ICL—Auckland CBD business pathway (site author studies here); international fees often ~NZD 23k–48.5k by level, plus enrolment/materials; use your offer for promos. https://icl.ac.nz/",
      "Yoobee—creative/digital (animation, design, software); diplomas/bachelor years often ~NZD 27,300 plus resource fees. https://yoobee.ac.nz/",
      "NZSE/NZSEG—skills-to-work (IT, business, analytics, teaching); wide fee spread ~NZD 18.9k–35.5k+. “NESEG” is usually a misspelling of NZSEG. https://nzse.ac.nz/",
      "Future Skills—Queen Street Auckland; applied management/construction-related and some master’s; list prices ~NZD 23.9k–40.5k, scholarships often change the net fee. https://www.futureskills.co.nz/",
      {
        "type": "image",
        "src": "/images/article-auckland-cbd.png",
        "alt": "Auckland CBD street",
        "caption": "ICL and Future Skills paths are often CBD-based—convenient, but rent is usually higher."
      },
      {
        "type": "h2",
        "text": "Subject mapping"
      },
      "Business → ICL, AIS, Future Skills, NZSE; IT/software → Yoobee, AIS, NZSE, Future Skills; hospitality → AIS, ICL; creative → Yoobee.",
      "Keep one primary + one backup, and line up list price, promo, materials and a year of rent. Use the consultation form when you need a tighter shortlist."
    ]
  },
  {
    "slug": "school-ais",
    "guideId": "study",
    "titleZh": "AIS 奥克兰商学院：专业、学费与适合谁",
    "titleEn": "AIS Auckland: programmes, fees and who it suits",
    "excerptZh": "Auckland Institute of Studies：商科、IT、酒店与语言衔接的实用对照。",
    "excerptEn": "Auckland Institute of Studies: business, IT, hospitality and English pathways.",
    "image": "/images/study-feature.png",
    "imageAltZh": "AIS 奥克兰私立学院",
    "imageAltEn": "AIS Auckland private college",
    "website": "https://ais.ac.nz/",
    "bodyZh": [
      "AIS（Auckland Institute of Studies）是奥克兰常见的私立培训机构（PTE）。中文资料里有时写成「奥克兰商学院」等，名称不统一——选校、交费、签证材料一律以官网与 NZQA 注册全名为准。",
      "官网：https://ais.ac.nz/ ——学费表、课程级别、开学季与英语要求都以这里和 Offer 为准，不要只听口头摘要。",
      {
        "type": "image",
        "src": "/images/article-campus-class.png",
        "alt": "校园课堂",
        "caption": "AIS 路径偏应用型商科/IT/酒店，适合先锁定专业方向再比学费。"
      },
      {
        "type": "h2",
        "text": "适合谁，不适合谁"
      },
      "适合：想在奥克兰读应用型商科、IT、酒店管理；需要 NZCEL/语言班再衔接主课；把文凭/研文当作较短升学路径并认真算预算的人。",
      "不太适合：目标是综合大学研究型硕士、强学术导师制，或只追求「八大名校」叙事的人——那是另一条赛道。",
      {
        "type": "h2",
        "text": "常见课程方向"
      },
      "商务与管理类文凭/本科、IT 相关课程、酒店与旅游管理、英语（含 NZCEL），以及部分研文与硕士（如 MBA、Master of IT 一类）。同一学校不同课的 NZQA 级别、时长与英语要求差很多，短名单前务必点开具体 programme 页。",
      "对照问题时可问招生办：课程是 Level 几、整课几个月、有无实习/项目课、国际生本季是否仍招生。",
      {
        "type": "h2",
        "text": "学费与隐藏成本"
      },
      "国际生近年公开材料约数：一年制文凭/研文常见约 NZD 22,000–27,000；本科常见约 NZD 22,000–24,000/年；MBA / Master of IT 一类硕士常见约 NZD 40,000 量级（有的按整课、有的按年）。另计报名费、材料费、保险与生活费。",
      "促销与奖学金会变。把「标价 / 可能成交价 / 材料费」三列写进表，再和 ICL、Future Skills 比。",
      {
        "type": "image",
        "src": "/images/article-shared-flat.png",
        "alt": "学生合租住所",
        "caption": "奥克兰房租常常比学费差额更伤预算，选校时把一年房租算进去。"
      },
      {
        "type": "h2",
        "text": "英语、申请与下一步"
      },
      "多数主课接受 IELTS Academic 或 PTE Academic；不够分时常见语言班或 NZCEL 衔接。把目标课的 English requirements 截图存档。",
      "申请前核对：NZQA 批准与级别、开学季与时长、学费计价方式、Conditional Offer 条件。需要 2–3 所对照时，可用咨询表整理学历、工作与资金情况。"
    ],
    "bodyEn": [
      "AIS (Auckland Institute of Studies) is a commonly discussed Auckland PTE. Chinese nicknames vary—always use the official/NZQA name for applications, payments and visas.",
      "Official site: https://ais.ac.nz/ — fees, levels, intakes and English rules live here and on your offer letter.",
      {
        "type": "image",
        "src": "/images/article-campus-class.png",
        "alt": "Campus classroom",
        "caption": "AIS leans applied business/IT/hospitality—lock the subject first, then compare fees."
      },
      {
        "type": "h2",
        "text": "Who it suits"
      },
      "Good fit: applied business, IT or hospitality in Auckland; NZCEL/pathway English needs; shorter diploma/PGDip pathways with a clear budget.",
      "Less fit: research-university master’s goals or an “eight universities” narrative—that is a different track.",
      {
        "type": "h2",
        "text": "Typical programmes"
      },
      "Business/management diplomas and bachelor’s, IT-related study, hospitality/tourism, English including NZCEL, plus some graduate diplomas and master’s (e.g. MBA / Master of IT). Levels and English rules differ by programme—open the exact page.",
      "Ask admissions: NZQA level, months, placements/projects, and whether international seats are open this intake.",
      {
        "type": "h2",
        "text": "Fees and extras"
      },
      "Approximate international fees: diploma/PGDip years often ~NZD 22,000–27,000; bachelor ~NZD 22,000–24,000/year; MBA / Master of IT-type study often around ~NZD 40,000. Add enrolment, materials, insurance and living costs.",
      "Promos change. Line up list price / likely offer price / materials, then compare with ICL and Future Skills.",
      {
        "type": "image",
        "src": "/images/article-shared-flat.png",
        "alt": "Shared student flat",
        "caption": "Auckland rent can outweigh tuition gaps—budget a full year of housing."
      },
      {
        "type": "h2",
        "text": "English and next steps"
      },
      "IELTS Academic or PTE Academic is common; pathway English or NZCEL may bridge in. Save the official English requirements for your programme.",
      "Before applying: NZQA approval, intake, fee structure and conditional-offer terms. Use the consultation form to compare 2–3 options."
    ]
  },
  {
    "slug": "school-icl",
    "guideId": "study",
    "titleZh": "ICL 商学院：课程路径、学费与就读体验要点",
    "titleEn": "ICL Business School: pathways, fees and practical notes",
    "excerptZh": "奥克兰 CBD 的 ICL：商科管理、信息化与研文/硕士路径怎么看。",
    "excerptEn": "ICL in Auckland CBD: business, informatics and graduate pathways explained.",
    "image": "/images/study-feature.png",
    "imageAltZh": "ICL 奥克兰 CBD 商学院",
    "imageAltEn": "ICL Auckland CBD business school",
    "website": "https://icl.ac.nz/",
    "bodyZh": [
      "ICL（ICL Graduate Business School / ICL Education）位于奥克兰 CBD，是站长目前就读的商学院路径。选校材料请核对官方名称与 NZQA 注册信息。",
      "官网：https://icl.ac.nz/ ——课程页、学费表与招生回复比中介海报可靠。",
      {
        "type": "image",
        "src": "/images/article-auckland-cbd.png",
        "alt": "奥克兰 CBD",
        "caption": "上课在市中心，兼职与办事方便，但房租和餐饮通常更贵。"
      },
      {
        "type": "h2",
        "text": "适合谁"
      },
      "希望读应用型商科/管理、商业信息、酒店旅游相关研文，或 ECE 幼教类研文，并接受较短、偏实务节奏的人。若你要大型综合大学校园或强研究型导师制，体验会不一样。",
      {
        "type": "h2",
        "text": "课程与学费"
      },
      "常见：商务文凭（Level 5 等）、管理/信息化研文与硕士、酒店旅游研究生课程、ECE 教学研文。开学季与班型会变，以官网为准。",
      "国际生 2025–2026 公开表常见约 NZD 23,000–48,500（Level 5 到 Level 9），另有报名费（公开材料常见约 NZD 260）与教材费。地区促销很常见——以 Offer 为准。",
      {
        "type": "image",
        "src": "/images/article-visa-docs.png",
        "alt": "申请与材料整理",
        "caption": "交押金前把语言、材料、缴费截止日写成清单，避免 Conditional Offer 条件拖到开学前。"
      },
      {
        "type": "h2",
        "text": "生活、对照与行动"
      },
      "CBD 通勤方便，但请单独列交通卡、合租押金、首月生活费。英语不够分时，问清语言衔接或条件录取规则。",
      "同一方向可保留 AIS 或 Future Skills 作备选。签证材料按移民局清单准备，不要默认「学校代办就不用自己核对」。背景复杂时用咨询表整理学历、工作与资金。"
    ],
    "bodyEn": [
      "ICL (ICL Graduate Business School / ICL Education) sits in Auckland CBD—the pathway the site author currently studies. Confirm the official NZQA-registered name.",
      "Official site: https://icl.ac.nz/ — programme pages and fee schedules beat agent posters.",
      {
        "type": "image",
        "src": "/images/article-auckland-cbd.png",
        "alt": "Auckland CBD",
        "caption": "Central classes help with part-time work, but rent and food usually cost more."
      },
      {
        "type": "h2",
        "text": "Who it suits"
      },
      "Applied business/management, business informatics, hospitality/tourism graduate study, or ECE teaching graduate diplomas with a practical cadence. Not the same as a large research campus.",
      {
        "type": "h2",
        "text": "Programmes and fees"
      },
      "Common types: business diplomas (e.g. Level 5), management/informatics graduate and master’s streams, hospitality/tourism postgraduate options, ECE teaching graduate diplomas.",
      "Approximate international fees (2025–2026 public schedules): about NZD 23,000–48,500 from Level 5 to Level 9, plus enrolment (often ~NZD 260) and materials. Promotions are common—only your offer counts.",
      {
        "type": "image",
        "src": "/images/article-visa-docs.png",
        "alt": "Application paperwork",
        "caption": "Before paying a deposit, list English, documents and payment deadlines from any conditional offer."
      },
      {
        "type": "h2",
        "text": "Living costs and next steps"
      },
      "Budget transport, bond and first-month living costs separately. Ask about pathway or conditional English rules if scores are short.",
      "Keep AIS or Future Skills as a backup. Prepare visa evidence yourself even if an agent helps. Use the consultation form for a tighter shortlist."
    ]
  },
  {
    "slug": "school-yoobee",
    "guideId": "study",
    "titleZh": "Yoobee：动画、设计与软件课程怎么选",
    "titleEn": "Yoobee: animation, design and software programmes",
    "excerptZh": "创意与数字技术导向：作品集、校区与大致学费。",
    "excerptEn": "Creative and digital tech pathways: portfolios, campuses and fee ranges.",
    "image": "/images/study-feature.png",
    "imageAltZh": "Yoobee 创意与数字学院",
    "imageAltEn": "Yoobee creative and digital college",
    "website": "https://yoobee.ac.nz/",
    "bodyZh": [
      "Yoobee（Yoobee Colleges / Yoobee College of Creative Innovation）以创意与数字技术见长，校区常见于奥克兰、惠灵顿、基督城等。它更像「作品集 + 技能输出」路线。",
      "官网：https://yoobee.ac.nz/ ——国际生招生、作品集要求与学费以官网当季信息为准。",
      {
        "type": "image",
        "src": "/images/article-creative-studio.png",
        "alt": "创意设计工作台",
        "caption": "申请时作品集质量往往和分数一样关键，提早按课程 brief 打磨项目。"
      },
      {
        "type": "h2",
        "text": "适合谁"
      },
      "目标在动画、数字媒体/设计、软件开发或软件工程，并愿意持续做作品集的人。若主要想读通用商科管理硕士，应优先对照 ICL、AIS、Future Skills。",
      {
        "type": "h2",
        "text": "课程、学费与城市"
      },
      "常见：创意基础证书、数字媒体/设计文凭、动画相关课、软件开发/软件工程文凭或本科。同一「设计」标题下课表与设备要求可能差很多。",
      "2026 公开价例：创意基础证书约 NZD 15,000 量级；多数文凭约 NZD 27,300；本科常见约 NZD 27,300/年；另收资源/行政费约 NZD 1,400–2,400。硬件要求高的课要单独问设备开销。",
      {
        "type": "image",
        "src": "/images/article-auckland-cbd.png",
        "alt": "城市学习与生活",
        "caption": "奥克兰机会多但房租高；惠灵顿、基督城生活费可能更友好，兼职市场也不同。"
      },
      {
        "type": "h2",
        "text": "申请要点"
      },
      "按课程页整理作品集（过程稿、最终稿、工具说明）；英语仍需满足 IELTS/PTE 等官方线。确认国际生招生与开学季是否对得上签证节奏。",
      "与 NZSE/AIS 的 IT 路径对比时，写清你是作品集导向还是技能就业导向，再用咨询表备注目标城市与预算。"
    ],
    "bodyEn": [
      "Yoobee focuses on creative and digital technology across campuses such as Auckland, Wellington and Christchurch. Think portfolio-and-skills output.",
      "Official site: https://yoobee.ac.nz/ — international intakes, portfolio rules and fees live there.",
      {
        "type": "image",
        "src": "/images/article-creative-studio.png",
        "alt": "Creative studio desk",
        "caption": "Portfolio quality often matters as much as scores—build projects to the brief early."
      },
      {
        "type": "h2",
        "text": "Who it suits"
      },
      "Animation, digital media/design, software development or software engineering students who will keep building a portfolio. For a general business master’s, compare ICL, AIS or Future Skills first.",
      {
        "type": "h2",
        "text": "Programmes, fees and cities"
      },
      "Typical areas: creative foundation certificates, digital media/design diplomas, animation-related study, software diplomas or bachelor’s. Titles can hide very different workloads.",
      "2026 public examples: foundation certificates around NZD 15,000; many diplomas around NZD 27,300; bachelor years often ~NZD 27,300 plus resource/admin fees ~NZD 1,400–2,400. Ask about equipment costs.",
      {
        "type": "image",
        "src": "/images/article-auckland-cbd.png",
        "alt": "City study life",
        "caption": "Auckland has more opportunities but higher rent; Wellington/Christchurch may be cheaper with different job markets."
      },
      {
        "type": "h2",
        "text": "Application tips"
      },
      "Prepare portfolio process/finals/tools notes; English must still meet official IELTS/PTE rules. Confirm international intakes against visa timing.",
      "When comparing NZSE/AIS IT paths, note portfolio-led vs skills-to-work goals in the consultation form."
    ]
  },
  {
    "slug": "school-nzse",
    "guideId": "study",
    "titleZh": "NZSE / NZSEG：技能课程、校区与学费区间",
    "titleEn": "NZSE / NZSEG: skills programmes, campuses and fees",
    "excerptZh": "IT、商务、数据分析与教学类路径；认准 NZSEG，别被 NESEG 误导。",
    "excerptEn": "IT, business, analytics and teaching paths—confirm NZSEG, not “NESEG”.",
    "image": "/images/study-feature.png",
    "imageAltZh": "NZSE 技能与教育学院",
    "imageAltEn": "NZSE skills and education college",
    "website": "https://nzse.ac.nz/",
    "bodyZh": [
      "NZSE（New Zealand Skills and Education College）隶属 NZSEG（New Zealand Skills and Education Group）。若材料写「NESEG」，多数是误写；请以 NZQA 注册名核对后再交钱。",
      "官网：https://nzse.ac.nz/ ；集团信息可对照 https://nzseg.com/。",
      {
        "type": "image",
        "src": "/images/article-skills-lab.png",
        "alt": "技能实训机房",
        "caption": "NZSE 路径偏技能就业，课表与校区绑定很紧，报名时确认上课 campus。"
      },
      {
        "type": "h2",
        "text": "适合谁"
      },
      "更看重技能就业、课程偏实务（IT 技术支持、网络云、商务、数据分析、工程或教学/幼教相关）的人。与 Yoobee 创意作品集、ICL CBD 商科硕士的决策逻辑不同。",
      {
        "type": "h2",
        "text": "校区与学费"
      },
      "常见讨论校区：奥克兰 CBD、New Lynn、Manukau 及怀卡托等。同一集团不同校区开课表可能不同。",
      "公开价例（约数，差很大）：IT Technical Support（Level 5）约 NZD 20,000；部分 Level 7 网络云约 NZD 20,000；数据分析研文约 NZD 18,900；教学类研文可到约 NZD 35,500；个别商务文凭更高（有页面约 NZD 38,000）。务必下载具体 programme 学费表。",
      {
        "type": "image",
        "src": "/images/article-campus-class.png",
        "alt": "应用型课堂",
        "caption": "教学类课程可能另有背景调查或实习安排，Offer 前就要问清时间线。"
      },
      {
        "type": "h2",
        "text": "怎么对照与行动"
      },
      "软件作品集 → Yoobee；奖学金净价应用管理 → Future Skills；CBD 商科硕士体验 → ICL；商科/酒店综合应用 → AIS。",
      "清单：核对 NZQA 名称 → 选定校区与级别 → 拉齐学费+房租 → 确认英语与实习相关规则。校名易混时，把中介材料截图备注进咨询表。"
    ],
    "bodyEn": [
      "NZSE sits under NZSEG. “NESEG” is usually a misspelling—confirm the NZQA-registered name before you pay.",
      "Official site: https://nzse.ac.nz/ (group: https://nzseg.com/).",
      {
        "type": "image",
        "src": "/images/article-skills-lab.png",
        "alt": "Skills training lab",
        "caption": "NZSE is skills-to-work oriented—confirm the exact campus for your programme."
      },
      {
        "type": "h2",
        "text": "Who it suits"
      },
      "IT support, network/cloud, business, analytics, engineering or teaching/ECE-related study with practical outcomes. Different from Yoobee portfolios or ICL CBD master’s paths.",
      {
        "type": "h2",
        "text": "Campuses and fees"
      },
      "Campuses often discussed: Auckland CBD, New Lynn, Manukau and Waikato. Timetables can differ by campus.",
      "Public examples (wide spread): IT Technical Support Level 5 ~NZD 20,000; some Level 7 network/cloud ~NZD 20,000; data analytics PGDip ~NZD 18,900; teaching PGDips can reach ~NZD 35,500; some business diplomas higher (~NZD 38,000). Download the exact schedule.",
      {
        "type": "image",
        "src": "/images/article-campus-class.png",
        "alt": "Applied classroom",
        "caption": "Teaching programmes may add checks or placements—ask about timelines before you accept."
      },
      {
        "type": "h2",
        "text": "Compare and act"
      },
      "Portfolio creative/software → Yoobee; scholarship-sensitive applied management → Future Skills; CBD business master’s → ICL; broader applied business/hospitality → AIS.",
      "Checklist: NZQA name → campus/level → fees plus rent → English/placement rules. Attach confusing agent paperwork notes in the consultation form."
    ]
  },
  {
    "slug": "school-future-skills",
    "guideId": "study",
    "titleZh": "Future Skills：应用管理、学费与奖学金怎么看",
    "titleEn": "Future Skills: applied management, fees and scholarships",
    "excerptZh": "Queen Street 国际校区：本科/研文/硕士标价与奖学金净价。",
    "excerptEn": "Queen Street campus: bachelor/PGDip/master’s list prices vs scholarship net fees.",
    "image": "/images/study-feature.png",
    "imageAltZh": "Future Skills 奥克兰国际校区",
    "imageAltEn": "Future Skills Auckland international campus",
    "website": "https://www.futureskills.co.nz/",
    "bodyZh": [
      "Future Skills（Future Skills Academy）国际生常讨论奥克兰 Queen Street 国际校区路径。宣传里的课程一律以官网当季与 NZQA 批准为准。",
      "官网：https://www.futureskills.co.nz/",
      {
        "type": "image",
        "src": "/images/article-auckland-cbd.png",
        "alt": "Queen Street 一带城市氛围",
        "caption": "市中心上课通勤方便，算预算时把奖学金后净价和房租一起看。"
      },
      {
        "type": "h2",
        "text": "适合谁"
      },
      "想读应用管理本科/研文/硕士，或建筑相关应用课，并会认真算「标价 vs 奖学金后净学费」的人。动画作品集优先看 Yoobee；技能 IT 支持对照 NZSE。",
      {
        "type": "h2",
        "text": "课程与标价"
      },
      "常见：Bachelor of Applied Management、应用管理研文/硕士、建筑或工料测量相关，以及部分 AI/IT 整合硕博宣传项目。先锁定级别再比学校。",
      "2026 材料常见标价：Bachelor of Applied Management 约 NZD 23,900/年；研文约 NZD 27,000；部分硕士整课约 NZD 40,500。关键看奖学金条款：是否自动、是否绑定国籍/开学季、重修是否仍享受。",
      {
        "type": "image",
        "src": "/images/article-visa-docs.png",
        "alt": "学费与 Offer 文件",
        "caption": "最终以 Offer 与缴费通知为准；口头「奖学金后只要xxx」不算数。"
      },
      {
        "type": "h2",
        "text": "下一步"
      },
      "下载最新学费与奖学金页 → 选定 1 个主申级别 → 再选 ICL 或 AIS 作备选 → 用咨询表填写学历、预算与开学目标。",
      "英语与材料按课程页准备；硕士/研文常见本科学历与成绩要求。收到 Conditional Offer 后逐条做成日期表。"
    ],
    "bodyEn": [
      "Future Skills international discussions often centre on the Auckland Queen Street campus. Verify current NZQA-approved programmes on the official site.",
      "Official site: https://www.futureskills.co.nz/",
      {
        "type": "image",
        "src": "/images/article-auckland-cbd.png",
        "alt": "Central Auckland atmosphere",
        "caption": "Convenient for commuting—compare scholarship-adjusted fees with rent."
      },
      {
        "type": "h2",
        "text": "Who it suits"
      },
      "Applied management (bachelor/PGDip/master’s) or construction-related applied study, with careful list-vs-net fee maths. Animation portfolios → Yoobee; skills IT support → NZSE.",
      {
        "type": "h2",
        "text": "Programmes and list prices"
      },
      "Typical: Bachelor of Applied Management, applied management PGDip/master’s, construction/QS-related courses, and some AI/IT-integrated postgraduate marketing. Lock the level first.",
      "2026 public list prices often include bachelor ~NZD 23,900/year, PGDip ~NZD 27,000, some master’s packages ~NZD 40,500. Read scholarship eligibility and repeat-paper rules.",
      {
        "type": "image",
        "src": "/images/article-visa-docs.png",
        "alt": "Offer and fee documents",
        "caption": "Your offer and invoice are the source of truth—not verbal “scholarship prices”."
      },
      {
        "type": "h2",
        "text": "Next steps"
      },
      "Download fees/scholarship pages → choose one primary level → keep ICL or AIS as backup → use the consultation form with education, budget and intake goals.",
      "Follow English and academic requirements on the programme page; turn conditional-offer terms into a dated checklist."
    ]
  },
  {
    "slug": "nz-private-providers",
    "guideId": "study",
    "titleZh": "五所私立/技能学校怎么对照短名单",
    "titleEn": "Comparing five private/skills providers for a shortlist",
    "excerptZh": "先定专业与预算，再在 AIS、ICL、Yoobee、NZSE、Future Skills 里做 2–3 所组合。",
    "excerptEn": "Lock subject and budget first, then pick 2–3 from AIS, ICL, Yoobee, NZSE and Future Skills.",
    "image": "/images/study-feature.png",
    "imageAltZh": "新西兰私立学院与技能学校",
    "imageAltEn": "A New Zealand private college campus",
    "bodyZh": [
      "短名单别从「名气」起，从三件事起：专业方向、可接受学费上限（含一年奥克兰房租）、英语现状（能否直入 / 需要 NZCEL 或语言班）。",
      "总览见《学费与怎么选》；细节见 AIS / ICL / Yoobee / NZSE / Future Skills 独立文章，并点开官网学费页交叉验证。",
      {
        "type": "image",
        "src": "/images/article-campus-class.png",
        "alt": "选校对比场景",
        "caption": "短名单先定专业、预算和英语，再打开各校专文细看。"
      },
      "偏商科管理、想读研文/硕士且希望在奥克兰 CBD：优先对照 ICL 与 Future Skills，AIS 作应用型本科/研文备选。",
      "偏 IT 技术支持、网络云、数据分析就业课：对照 NZSE 与 AIS；软件/数字作品集路线看 Yoobee；AI/IT 硕可看 Future Skills 当季项目。",
      "偏酒店、旅游、商务实践课：AIS 与 ICL 相关文凭/研文更常进入讨论；创意动画设计几乎总是 Yoobee 优先。",
      {
        "type": "h2",
        "text": "做成一张表再决定"
      },
      "每方向保留 1 所主申 + 1 所备选；列「标价 / 促销价 / 材料费 / 一年房租 / 英语缺口」。表填完再交押金。",
      "若两所学费接近，优先看：开学季是否赶得上、语言条件是否现实、校区通勤是否可接受。",
      {
        "type": "image",
        "src": "/images/article-visa-docs.png",
        "alt": "材料与决策清单",
        "caption": "把 Offer 条件与签证材料时间写进同一日历，比临出发前赶工稳得多。"
      }
    ],
    "bodyEn": [
      "Start a shortlist from subject, max tuition (plus Auckland rent), and English readiness—not brand names.",
      "Use the overview article plus each school deep-dive, then verify fees on official sites.",
      {
        "type": "image",
        "src": "/images/article-campus-class.png",
        "alt": "School comparison",
        "caption": "Lock subject, budget and English first, then read each school article."
      },
      "Business/management with graduate diploma or master’s in Auckland CBD: compare ICL and Future Skills first; keep AIS as backup.",
      "IT support, network/cloud, analytics-to-work: compare NZSE and AIS; portfolio software/digital paths → Yoobee; AI/IT master’s → Future Skills.",
      "Hospitality/tourism/applied business: AIS and ICL; creative animation/design almost always starts with Yoobee.",
      {
        "type": "h2",
        "text": "Make one comparison sheet"
      },
      "Keep one primary + one backup per direction; columns for list price, promo, materials, yearly rent and English gaps.",
      "If fees are close, prioritise intake timing, realistic English conditions and commute.",
      {
        "type": "image",
        "src": "/images/article-visa-docs.png",
        "alt": "Decision checklist",
        "caption": "Put offer conditions and visa tasks on one calendar before you pay a deposit."
      }
    ]
  },
  {
    "slug": "nz-application-timeline",
    "guideId": "study",
    "titleZh": "新西兰留学申请时间线（附清单）",
    "titleEn": "A New Zealand application timeline and checklist",
    "excerptZh": "从定专业到拿 offer、办签证，按月份倒推更不容易漏项。",
    "excerptEn": "Work backwards from intake to offers and visas so fewer items slip.",
    "image": "/images/study-feature.png",
    "imageAltZh": "新西兰大学校园",
    "imageAltEn": "A New Zealand university campus",
    "bodyZh": [
      "申请不是从填表开始，而是从时间倒推开始。先确定目标开学季（常见 2 月 / 7 月），再往前排语言考试、材料、申请与签证。",
      {
        "type": "h2",
        "text": "开学前 9–12 个月"
      },
      {
        "type": "image",
        "src": "/images/article-visa-docs.png",
        "alt": "申请文件与时间规划",
        "caption": "先锁定开学季，再倒推语言考试、网申、押金与签证。"
      },
      "确定专业与 3–5 所学校短名单；准备成绩单、毕业证明/在读证明；规划雅思/PTE 考试时间，并预留一次重考缓冲。",
      {
        "type": "h2",
        "text": "开学前 6–9 个月"
      },
      "提交网申，准备个人陈述、简历、推荐信或作品集；跟进补件邮件，别让申请停在 incomplete。",
      {
        "type": "h2",
        "text": "开学前 3–6 个月"
      },
      "比较 offer 条件；接受并缴费；启动学生签证材料（资金、保险、录取文件等，以移民局要求为准）。",
      {
        "type": "h2",
        "text": "开学前 1–2 个月"
      },
      "安排住宿、接机、银行卡与手机卡；核对注册与 Orientation；文件电子版与纸质版各留一份。",
      "简易清单：护照有效期、成绩单、语言成绩、录取/COE、资金证明、保险、住址与紧急联系人。每完成一项就打勾。",
      "私立学院路径（AIS/ICL/Yoobee/NZSE/Future Skills）同样要按级别核对英语与开学季，不要套用大学通用时间表。",
      {
        "type": "image",
        "src": "/images/article-arrival.png",
        "alt": "出发前准备",
        "caption": "机票日期尽量灵活，等签证与住宿确认后再定死行程。"
      }
    ],
    "bodyEn": [
      "Applications start with a calendar. Lock your intake (often February or July), then work backwards.",
      {
        "type": "h2",
        "text": "9–12 months out"
      },
      {
        "type": "image",
        "src": "/images/article-visa-docs.png",
        "alt": "Application planning",
        "caption": "Lock the intake, then work backwards through tests, applications, deposits and visa."
      },
      "Shortlist 3–5 programmes; prepare transcripts; book IELTS/PTE with buffer for a retake.",
      {
        "type": "h2",
        "text": "6–9 months out"
      },
      "Submit applications; draft statement/CV/references/portfolio; clear incomplete emails quickly.",
      {
        "type": "h2",
        "text": "3–6 months out"
      },
      "Compare offers, accept and pay, then start the student visa file using Immigration NZ’s checklist.",
      {
        "type": "h2",
        "text": "1–2 months out"
      },
      "Arrange housing, arrival, banking and a SIM; confirm enrolment/orientation; keep digital and paper copies.",
      "Checklist: passport, transcripts, English score, offer/COE, funds, insurance, address and emergency contact.",
      "PTE pathways (AIS/ICL/Yoobee/NZSE/Future Skills) still need level-specific English and intake checks—do not copy a generic university timeline blindly.",
      {
        "type": "image",
        "src": "/images/article-arrival.png",
        "alt": "Before departure",
        "caption": "Keep flights flexible until visa and housing are clearer."
      }
    ]
  },
  {
    "slug": "student-visa-basics",
    "guideId": "study",
    "titleZh": "学生签证材料与常见卡点",
    "titleEn": "Student visa documents and common blockers",
    "excerptZh": "资金、录取、保险与行程说明——按移民局清单准备，别凭经验猜测。",
    "excerptEn": "Funds, offer, insurance and travel plans—follow Immigration NZ, not guesswork.",
    "image": "/images/study-feature.png",
    "imageAltZh": "新西兰留学场景",
    "imageAltEn": "New Zealand study and life scene",
    "bodyZh": [
      "学生签证以 Immigration New Zealand 当前要求为准。核心通常包括：有效护照、录取/缴费证明、资金证明、保险安排，以及真实的学习计划说明。",
      "资金证明要「说得通」：存款时长、资金来源、学费+生活费是否覆盖。临时大额转入又说不清来源，是常见补件原因。",
      {
        "type": "image",
        "src": "/images/article-visa-docs.png",
        "alt": "签证材料桌面",
        "caption": "签证材料桌面"
      },
      "收到 Conditional Offer 先分清条件：语言、成绩单原件、押金等。条件未完成就递签，容易反复。",
      "保险：很多学校要求注册前已有合适医疗保险。买之前核对保障范围与入学要求。",
      "递交后保持邮箱与 Immigrate 账户畅通，补件尽量一次给齐。政策会变，临交前再核对官网。",
      {
        "type": "h2",
        "text": "流水与大额说明怎么写清楚"
      },
      "把工资、父母资助、卖房/理财赎回等对应到具体月份；咨询表里的「大额进账说明」就是为签证解释准备的。",
      "材料扫描件命名规范（护照、Offer、存款、流水），方便补件时迅速上传。",
      {
        "type": "image",
        "src": "/images/article-shared-flat.png",
        "alt": "稳定的学习与生活安排",
        "caption": "签证官也看你的住宿与行程是否合理，短租安排可以先写进说明。"
      }
    ],
    "bodyEn": [
      "Always follow the current Immigration NZ checklist: passport, offer/fee evidence, funds, insurance and a credible study plan.",
      "Funds must make sense: history, source, and coverage of tuition plus living costs. Unexplained large deposits often trigger more questions.",
      {
        "type": "image",
        "src": "/images/article-visa-docs.png",
        "alt": "Visa documents desk",
        "caption": "Visa documents desk"
      },
      "Separate language, document and deposit conditions on a conditional offer before you lodge.",
      "Confirm insurance meets school rules before enrolment.",
      "Monitor email and your immigration account; recheck the official site before you submit.",
      {
        "type": "h2",
        "text": "Explain large transfers clearly"
      },
      "Map salary, parental support or asset sales to months in your statements—the consultation form’s large-transfer note helps.",
      "Name scans clearly so you can upload quickly if Immigration asks for more.",
      {
        "type": "image",
        "src": "/images/article-shared-flat.png",
        "alt": "Settled living plans",
        "caption": "A credible housing plan helps your overall story—short stays are fine at first."
      }
    ]
  },
  {
    "slug": "english-test-guide",
    "guideId": "study",
    "titleZh": "雅思与 PTE：分数怎么够用",
    "titleEn": "IELTS and PTE: scores that actually work",
    "excerptZh": "先查课程官网英语要求，再选考试；PTE 与雅思都要看总分和小分。",
    "excerptEn": "Check the course page first, then choose a test—overall and skill scores both matter.",
    "image": "/images/study-feature.png",
    "imageAltZh": "新西兰留学场景",
    "imageAltEn": "New Zealand study and life scene",
    "bodyZh": [
      "私立学院与技能学校（如 AIS、ICL、Yoobee、NZSE、Future Skills）多数接受 IELTS Academic 或 PTE Academic；也常见 NZCEL 或语言班衔接。以课程页为准。",
      "备考：先模考定位弱项（写作/口语常见）。时间紧就比较考位与出分速度，再决定雅思或 PTE。",
      {
        "type": "image",
        "src": "/images/article-campus-class.png",
        "alt": "语言学习课堂",
        "caption": "语言学习课堂"
      },
      "差 0.5 分时：看语言班、NZCEL、内部测试或有条件录取，别盲目重考耽误开学季。",
      "成绩单公证/翻译与语言成绩并行准备，避免语言过了却卡在成绩单。",
      "到校后仍要练学术写作与讨论——入学分只是门槛。",
      {
        "type": "h2",
        "text": "小分与课程级别"
      },
      "硕士/研文与文凭的小分要求可能不同；同一学校不同课也不一样。把目标课要求抄进备考表。",
      "考试当天策略：留足证件与到达时间；PTE/雅思规则以官方说明为准。",
      {
        "type": "image",
        "src": "/images/article-visa-docs.png",
        "alt": "成绩与申请并行",
        "caption": "语言成绩出来后立刻推进网申与补件，别空等下一个开学季。"
      }
    ],
    "bodyEn": [
      "Private/skills providers usually accept IELTS Academic or PTE Academic; NZCEL/pathway English is common. Use the official page.",
      "Mock-test first; compare dates and result speed if time is tight.",
      {
        "type": "image",
        "src": "/images/article-campus-class.png",
        "alt": "Language study classroom",
        "caption": "Language study classroom"
      },
      "If you miss by a little, check pathway options before delaying an intake.",
      "Run transcript work in parallel with English prep.",
      "Keep building academic skills after arrival—entry scores are only a gate.",
      {
        "type": "h2",
        "text": "Skill scores and levels"
      },
      "Master’s, PGDip and diploma cut-offs can differ—even inside one school. Copy the exact target into your study plan.",
      "On test day, follow official ID and timing rules.",
      {
        "type": "image",
        "src": "/images/article-visa-docs.png",
        "alt": "Scores and applications together",
        "caption": "As soon as results land, push applications—do not wait idle for the next intake."
      }
    ]
  },
  {
    "slug": "offer-acceptance-checklist",
    "guideId": "study",
    "titleZh": "拿到 Offer 后做什么（清单）",
    "titleEn": "Got an offer? Next-step checklist",
    "excerptZh": "分清条件、缴费、接受 offer、签证与住宿——按顺序推进。",
    "excerptEn": "Conditions, fees, acceptance, visa and housing—move in order.",
    "image": "/images/study-feature.png",
    "imageAltZh": "新西兰留学场景",
    "imageAltEn": "New Zealand study and life scene",
    "bodyZh": [
      "先把 Offer 读完：课程名、开学日、学费、条件（语言/材料/押金截止日期）。截图或下载 PDF 存档。",
      "多份 Offer 时对比：总时长、是否含实习、城市房租、语言条件能否在截止日期前完成。",
      {
        "type": "image",
        "src": "/images/article-visa-docs.png",
        "alt": "Offer 与缴费文件",
        "caption": "Offer 与缴费文件"
      },
      "接受 Offer 与缴费按学校说明操作，保留收据；确认 COE/缴费证明是否已生成。",
      "同步启动：签证材料、保险、住宿意向、灵活机票。",
      "入学前再核：注册、Orientation、学生账号与邮箱。",
      {
        "type": "h2",
        "text": "缴费前后 48 小时"
      },
      "缴费前再确认账户名与金额；缴费后保存水单，并邮件确认学校已收到。",
      "若要放弃某份 Offer，按学校方式书面取消，避免重复占位或误解。",
      {
        "type": "image",
        "src": "/images/article-arrival.png",
        "alt": "行前安排",
        "caption": "住宿未定时可先短租 2–4 周，落地后再找长租更稳。"
      }
    ],
    "bodyEn": [
      "Read the offer fully and save the PDF.",
      "Compare duration, placements, rent and whether English conditions are realistic.",
      {
        "type": "image",
        "src": "/images/article-visa-docs.png",
        "alt": "Offer and payment papers",
        "caption": "Offer and payment papers"
      },
      "Accept/pay as instructed; confirm COE/payment letters for the visa.",
      "Start visa, insurance, housing and flexible flights in parallel.",
      "Confirm enrolment, orientation and student logins before arrival.",
      {
        "type": "h2",
        "text": "48 hours around payment"
      },
      "Recheck account name and amount; save proof and email the school for receipt confirmation.",
      "Decline unused offers in writing so places are not held by mistake.",
      {
        "type": "image",
        "src": "/images/article-arrival.png",
        "alt": "Pre-arrival plans",
        "caption": "A 2–4 week short stay is fine while you search for a longer flat."
      }
    ]
  },
  {
    "slug": "tuition-living-budget",
    "guideId": "study",
    "titleZh": "学费与生活费：怎么做年度预算",
    "titleEn": "Tuition and living costs: a yearly budget",
    "excerptZh": "把学费、房租、交通、保险分项算清，奥克兰与其他城市差很多。",
    "excerptEn": "Split tuition, rent, transport and insurance—Auckland differs a lot from other cities.",
    "image": "/images/study-feature.png",
    "imageAltZh": "新西兰留学场景",
    "imageAltEn": "New Zealand study and life scene",
    "bodyZh": [
      "预算至少分五块：学费、房租、日常饮食、交通通讯、保险杂费。材料费、报名费单独列。",
      "房租是最大变量：AIS / ICL / Yoobee / NZSE / Future Skills 多在奥克兰，选校时把学费差和房租一起算。",
      {
        "type": "image",
        "src": "/images/article-supermarket.png",
        "alt": "日常开销与采购",
        "caption": "日常开销与采购"
      },
      "打工收入别写进「必须依赖」的预算——工时有上限，课业重时排班不稳。",
      "预留应急金：押金、家具、教材、体检或补考。",
      "做表：每月固定支出 + 开学月一次性支出，咨询时可带上对照各校学费。",
      {
        "type": "h2",
        "text": "奥克兰样本怎么用"
      },
      "可先用《留学生一个月生活费怎么算》里的月度区间 × 12，再加上学费与保险，得到「第一年现金需求」。",
      "汇率波动时，按略保守汇率估算人民币备款更稳。",
      {
        "type": "image",
        "src": "/images/article-shared-flat.png",
        "alt": "房租占比",
        "caption": "合租能显著降低月度总成本，独居 studio 要单独加一截预算。"
      }
    ],
    "bodyEn": [
      "Budget tuition, rent, food, transport/phone and insurance/misc separately.",
      "Auckland rent can dominate for the main private/skills shortlist—compare with tuition gaps.",
      {
        "type": "image",
        "src": "/images/article-supermarket.png",
        "alt": "Daily spending and groceries",
        "caption": "Daily spending and groceries"
      },
      "Do not depend on work income in the must-have budget.",
      "Keep a buffer for bond, furniture, books and medical costs.",
      "Bring a simple yearly sheet to consultations when shortlisting.",
      {
        "type": "h2",
        "text": "Using an Auckland sample"
      },
      "Multiply the monthly ranges in the living-budget article by 12, then add tuition and insurance for year-one cash need.",
      "Use a slightly conservative CNY exchange assumption when saving funds.",
      {
        "type": "image",
        "src": "/images/article-shared-flat.png",
        "alt": "Rent share",
        "caption": "Flatting lowers totals a lot versus a studio alone."
      }
    ]
  },
  {
    "slug": "seek-trademe-jobs",
    "guideId": "career",
    "titleZh": "在 Seek 与 Trade Me 找工作：实用建议",
    "titleEn": "Finding work on Seek and Trade Me: practical tips",
    "excerptZh": "两个平台怎么用、简历怎么写、学生签证工时要注意什么。",
    "excerptEn": "How to use both platforms, write a local CV, and mind student work-hour rules.",
    "image": "/images/career-feature.png",
    "imageAltZh": "奥克兰工作与城市生活",
    "imageAltEn": "Work and city life in Auckland",
    "bodyZh": [
      "在新西兰找兼职或全职，最常用 Seek 和 Trade Me Jobs。零售、餐饮、客服、仓库、行政用它们就够起步；专业岗更多在 Seek 与 LinkedIn。",
      "Seek：量大、筛选细。用关键词 + 区域，开 Email alerts，先读 Requirements 再投。",
      {
        "type": "image",
        "src": "/images/article-job-search.png",
        "alt": "在 Seek 与 Trade Me 找工作：实用建议",
        "caption": "在 Seek 与 Trade Me 找工作：实用建议"
      },
      "Trade Me Jobs：本地中小商家多，适合附近兼职与临时班；投前问清排班、时薪、交通。",
      "简历一页、英文、结果导向；Cover letter 三五段说清匹配点。",
      "学生工时以 Immigration NZ 最新规定为准。每周稳定投 8–15 个匹配岗，比一天海投更有效。",
      {
        "type": "h2",
        "text": "投递后的跟进"
      },
      "投出 5–7 天可礼貌跟进一次；面试后 24 小时内短感谢即可。",
      "每次面试用笔记记录：问了什么、哪题卡壳、时薪与排班，方便下一封申请。",
      {
        "type": "image",
        "src": "/images/article-auckland-cbd.png",
        "alt": "城市通勤找工",
        "caption": "选岗时把通勤时间算进「值不值得」，比只看时薪更实际。"
      }
    ],
    "bodyEn": [
      "Start with Seek and Trade Me Jobs for most entry roles; use LinkedIn for more professional paths.",
      "Seek: filters and alerts; read requirements before applying.",
      {
        "type": "image",
        "src": "/images/article-job-search.png",
        "alt": "Finding work on Seek and Trade Me: practical tips",
        "caption": "Finding work on Seek and Trade Me: practical tips"
      },
      "Trade Me Jobs: strong for local casual/part-time roles—ask about roster and pay.",
      "One-page English CV; short cover letter with clear fit.",
      "Follow current Immigration NZ hour rules; 8–15 matched applications a week beats spam.",
      {
        "type": "h2",
        "text": "Follow-up"
      },
      "One polite follow-up after 5–7 days is fine; a short thank-you within 24 hours after interviews helps.",
      "Keep interview notes: questions, sticky moments, pay and roster.",
      {
        "type": "image",
        "src": "/images/article-auckland-cbd.png",
        "alt": "Commuting to work",
        "caption": "Factor commute time into whether a wage is worth it."
      }
    ]
  },
  {
    "slug": "nz-cv-cover-letter",
    "guideId": "career",
    "titleZh": "新西兰简历与 Cover Letter 怎么写",
    "titleEn": "How to write an NZ CV and cover letter",
    "excerptZh": "一页简历、结果导向、关键词对齐职位——比华丽模板更重要。",
    "excerptEn": "One page, outcomes and keyword fit beat fancy templates.",
    "image": "/images/career-feature.png",
    "imageAltZh": "奥克兰工作与城市生活",
    "imageAltEn": "Work and city life in Auckland",
    "bodyZh": [
      "本地简历通常一页：联系方式、教育、经历、技能。不必放照片、年龄、婚姻状况。",
      "经历用动词开头 + 结果；针对每个岗位微调关键词。",
      {
        "type": "image",
        "src": "/images/article-job-search.png",
        "alt": "新西兰简历与 Cover Letter 怎么写",
        "caption": "新西兰简历与 Cover Letter 怎么写"
      },
      "Cover letter：自我介绍、匹配点、可立即贡献的能力，三段左右。",
      "文件命名：Firstname_Lastname_CV.pdf。投前检查错别字与联系方式。",
      "没有本地经验时，突出可迁移技能：顾客服务、排班协作、收银、库存、课堂项目。",
      {
        "type": "h2",
        "text": "常见扣分项"
      },
      "模板花哨但信息密度低、中英混排混乱、把微信当唯一联系方式——都容易减分。",
      {
        "type": "image",
        "src": "/images/article-skills-lab.png",
        "alt": "技能与项目展示",
        "caption": "课程项目也可写成经历：你负责什么、用什么工具、结果是什么。"
      }
    ],
    "bodyEn": [
      "One-page NZ CV: contact, education, experience, skills—no photo/age/marital status.",
      "Verb + outcome bullets; mirror role keywords each time.",
      {
        "type": "image",
        "src": "/images/article-job-search.png",
        "alt": "How to write an NZ CV and cover letter",
        "caption": "How to write an NZ CV and cover letter"
      },
      "Short cover letter: who you are, fit, contribution.",
      "Clear PDF names; spell-check contacts.",
      "No local experience yet? Emphasise transferable service, teamwork and project skills.",
      {
        "type": "h2",
        "text": "Common score-killers"
      },
      "Fancy low-density templates, messy bilingual layouts, or WeChat-only contact details hurt you.",
      {
        "type": "image",
        "src": "/images/article-skills-lab.png",
        "alt": "Skills and projects",
        "caption": "Course projects count—role, tools and outcome."
      }
    ]
  },
  {
    "slug": "interview-star",
    "guideId": "career",
    "titleZh": "本地面试：用 STAR 讲清楚经历",
    "titleEn": "NZ interviews: tell your story with STAR",
    "excerptZh": "行为面试常见，准备两个真实例子比背稿更管用。",
    "excerptEn": "Behavioural interviews are common—two real examples beat memorised scripts.",
    "image": "/images/career-feature.png",
    "imageAltZh": "奥克兰工作与城市生活",
    "imageAltEn": "Work and city life in Auckland",
    "bodyZh": [
      "常见问题：冲突、压力、失败复盘、为什么想做这份工。",
      "STAR：情境、任务、行动、结果；每个例子 1–2 分钟。",
      {
        "type": "image",
        "src": "/images/article-job-search.png",
        "alt": "本地面试：用 STAR 讲清楚经历",
        "caption": "本地面试：用 STAR 讲清楚经历"
      },
      "英文卡壳时先答结论再补细节，可请对方重复问题。",
      "当天：提前到、着装整洁、带纸质简历。",
      "没拿到也记录反馈：经验、英语还是排班不匹配。",
      {
        "type": "h2",
        "text": "两个备用故事就够"
      },
      "建议准备：一次协作冲突、一次在压力下交付。零售/餐饮经历完全可用。",
      {
        "type": "image",
        "src": "/images/article-auckland-cbd.png",
        "alt": "面试出行",
        "caption": "预留交通延误缓冲；视频面试则提前测摄像头与网络。"
      }
    ],
    "bodyEn": [
      "Common themes: conflict, pressure, failure lessons, motivation.",
      "STAR stories in 1–2 minutes each.",
      {
        "type": "image",
        "src": "/images/article-job-search.png",
        "alt": "NZ interviews: tell your story with STAR",
        "caption": "NZ interviews: tell your story with STAR"
      },
      "If English stalls, lead with the outcome; ask to repeat if needed.",
      "Arrive early, dress tidy, bring a paper CV.",
      "No offer still teaches—note the gap and adjust.",
      {
        "type": "h2",
        "text": "Two backup stories"
      },
      "Prepare one teamwork conflict and one under-pressure delivery—hospitality/retail counts.",
      {
        "type": "image",
        "src": "/images/article-auckland-cbd.png",
        "alt": "Getting to the interview",
        "caption": "Buffer for delays; for video interviews, test camera and network early."
      }
    ]
  },
  {
    "slug": "ird-work-hours",
    "guideId": "career",
    "titleZh": "IRD 税号与学生工时合规",
    "titleEn": "IRD number and lawful student work hours",
    "excerptZh": "先确认签证工时，再申请 IRD；发薪与报税才走得通。",
    "excerptEn": "Confirm visa hours first, then get an IRD number for payroll and tax.",
    "image": "/images/career-feature.png",
    "imageAltZh": "奥克兰工作与城市生活",
    "imageAltEn": "Work and city life in Auckland",
    "bodyZh": [
      "能否打工、每周几小时，以签证条件与 Immigration NZ 最新规定为准。",
      "有工作后尽快申请 IRD，方便发薪与扣税。",
      {
        "type": "image",
        "src": "/images/article-visa-docs.png",
        "alt": "IRD 税号与学生工时合规",
        "caption": "IRD 税号与学生工时合规"
      },
      "确认时薪、排班、试用期；保留工资单。",
      "换工作更新银行与税务信息。",
      "不确定条款时查移民局或持牌顾问——合规比多上班重要。",
      {
        "type": "h2",
        "text": "排班怎么自查"
      },
      "用日历记录每周工时；开学季课业重时主动和雇主沟通减班，避免被动超工时。",
      {
        "type": "image",
        "src": "/images/article-job-search.png",
        "alt": "边读边工",
        "caption": "第一份工重点是准时与沟通，本地推荐比短期高薪更值钱。"
      }
    ],
    "bodyEn": [
      "Verify visa work rights and hours before accepting a roster.",
      "Get an IRD number promptly for payroll/tax.",
      {
        "type": "image",
        "src": "/images/article-visa-docs.png",
        "alt": "IRD number and lawful student work hours",
        "caption": "IRD number and lawful student work hours"
      },
      "Check pay, roster and trial terms; keep payslips.",
      "Update bank/tax details when jobs change.",
      "If unsure, check Immigration NZ or a licensed adviser.",
      {
        "type": "h2",
        "text": "Self-check your roster"
      },
      "Track weekly hours on a calendar; ask to reduce shifts in heavy study weeks.",
      {
        "type": "image",
        "src": "/images/article-job-search.png",
        "alt": "Study and work",
        "caption": "Reliability and references beat a short burst of high hours."
      }
    ]
  },
  {
    "slug": "nz-monthly-budget",
    "guideId": "life",
    "titleZh": "留学生一个月生活费怎么算",
    "titleEn": "A practical one-month NZ living budget",
    "excerptZh": "房租、饮食、日用品再加交通手机水电网——给奥克兰与其他城市各算一笔约数。",
    "excerptEn": "Rent, food, daily needs, plus transport, phone and bills—sample Auckland and cheaper-city totals.",
    "image": "/images/hero-coast.png",
    "imageAltZh": "新西兰日常生活",
    "imageAltEn": "Everyday life in New Zealand",
    "bodyZh": [
      "以下为约 2025–2026 年常见区间（纽币 NZD），以奥克兰为主；学费、保险、签证费另算。数字是约数，请再核当地房租与账单。",
      "房租：奥克兰合租单间大约 NZ$220–350/周；studio / 一居约 NZ$400–550+/周。其他城市合租常可更低。",
      {
        "type": "image",
        "src": "/images/article-supermarket.png",
        "alt": "留学生一个月生活费怎么算",
        "caption": "留学生一个月生活费怎么算"
      },
      "饮食：自己做饭约 NZ$350–500/月；含外食可到 NZ$400–650。日用品约 NZ$40–80。",
      "杂项：公交约 NZ$80–150；手机约 NZ$20–40；水电分摊约 NZ$40–80；宽带分摊约 NZ$20–40。",
      "样本合计（奥克兰合租）：节俭约 NZ$1,600–1,900；适中约 NZ$2,000–2,400。",
      {
        "type": "h2",
        "text": "怎么用这张表做决定"
      },
      "把月度生活费 × 在读月数，加上学费与保险，才是「要准备的现金」。汇率可按略保守估算折人民币。",
      "独居或要住 CBD 核心区，先把房租上调一档再谈「能不能去」。",
      {
        "type": "image",
        "src": "/images/article-shared-flat.png",
        "alt": "合租是控成本关键",
        "caption": "看房时问清电费网费是否另计，避免月度账单突然涨一截。"
      }
    ],
    "bodyEn": [
      "Approximate 2025–2026 NZD ranges centred on Auckland; tuition/insurance/visa are separate—verify locally.",
      "Rent: Auckland shared room ~NZ$220–350/week; studio/one-bed ~NZ$400–550+/week.",
      {
        "type": "image",
        "src": "/images/article-supermarket.png",
        "alt": "A practical one-month NZ living budget",
        "caption": "A practical one-month NZ living budget"
      },
      "Food: groceries ~NZ$350–500; with takeaways ~NZ$400–650; daily needs ~NZ$40–80.",
      "Extras: transport ~NZ$80–150; phone ~NZ$20–40; utilities ~NZ$40–80; broadband share ~NZ$20–40.",
      "Sample Auckland shared totals: thrifty ~NZ$1,600–1,900; mid ~NZ$2,000–2,400.",
      {
        "type": "h2",
        "text": "How to use the sample"
      },
      "Monthly living × study months + tuition + insurance = cash to prepare. Use a conservative CNY rate.",
      "Living alone or deep CBD? Raise the rent line before you decide.",
      {
        "type": "image",
        "src": "/images/article-shared-flat.png",
        "alt": "Flatting controls cost",
        "caption": "Ask whether power/internet are extra so bills do not surprise you."
      }
    ]
  },
  {
    "slug": "renting-guide",
    "guideId": "life",
    "titleZh": "新西兰租房：Trade Me 与合租注意点",
    "titleEn": "Renting in NZ: Trade Me and flatmate tips",
    "excerptZh": "看房要快、材料备齐；押金收据与租约条款必须看清。",
    "excerptEn": "Move fast with documents ready; read bond receipts and lease terms carefully.",
    "image": "/images/hero-coast.png",
    "imageAltZh": "新西兰日常生活",
    "imageAltEn": "Everyday life in New Zealand",
    "bodyZh": [
      "整租与独立房间多见 Trade Me Property；找室友常用 Flatmates。奥克兰竞争激烈，回复要快。",
      "看房带上：护照/签证页、录取或在读证明、资金说明、推荐信（如有）。",
      {
        "type": "image",
        "src": "/images/article-shared-flat.png",
        "alt": "新西兰租房：Trade Me 与合租注意点",
        "caption": "新西兰租房：Trade Me 与合租注意点"
      },
      "检查：租约时长、押金收据、暖气潮气、通勤、账单是否另计。",
      "合租前谈清清洁与客人规则。",
      "付押金走可追溯方式，保留记录；纠纷可了解 Tenancy Services。",
      {
        "type": "h2",
        "text": "看房当天问题清单"
      },
      "暖气是否够用、卫生间有无发霉、洗衣怎么安排、安静时段、是否允许短期转租。",
      "没看清合同不要付大额定金；不确定条款可先拍照发给朋友帮看。",
      {
        "type": "image",
        "src": "/images/article-arrival.png",
        "alt": "落地过渡住宿",
        "caption": "先短租再长租，能减少「盲签一年」的风险。"
      }
    ],
    "bodyEn": [
      "Trade Me Property for listings; Flatmates for shared rooms. Auckland is fast—reply quickly.",
      "Bring passport/visa, enrolment, funds evidence and references.",
      {
        "type": "image",
        "src": "/images/article-shared-flat.png",
        "alt": "Renting in NZ: Trade Me and flatmate tips",
        "caption": "Renting in NZ: Trade Me and flatmate tips"
      },
      "Check lease length, bond, damp/heating, commute and bill inclusions.",
      "Agree cleaning/guest rules before moving in.",
      "Pay via traceable channels; Tenancy Services guidance helps if issues arise.",
      {
        "type": "h2",
        "text": "Questions on viewing day"
      },
      "Heating, damp, laundry, quiet hours and subletting rules.",
      "Do not pay large holding deposits before you understand the agreement.",
      {
        "type": "image",
        "src": "/images/article-arrival.png",
        "alt": "Transitional stay",
        "caption": "Short stay first reduces the risk of blind year-long leases."
      }
    ]
  },
  {
    "slug": "bank-account-setup",
    "guideId": "life",
    "titleZh": "银行卡办理：四大行开户要点",
    "titleEn": "Opening a bank account: the main banks",
    "excerptZh": "护照、签证、地址与学生证明——预约国际学生开户更省事。",
    "excerptEn": "Passport, visa, address and student proof—book an international-student appointment.",
    "image": "/images/hero-coast.png",
    "imageAltZh": "新西兰日常生活",
    "imageAltEn": "Everyday life in New Zealand",
    "bodyZh": [
      "常见：ANZ、ASB、Westpac、BNZ。通常需要护照、签证/入境证明、地址证明与学生证明。",
      "可预约国际学生开户；部分支持预开户后落地激活。",
      {
        "type": "image",
        "src": "/images/article-visa-docs.png",
        "alt": "银行卡办理：四大行开户要点",
        "caption": "银行卡办理：四大行开户要点"
      },
      "问清月费、汇款费用、借记卡与网银激活。",
      "有 IRD 后发薪更顺；勿泄露验证码与密码。",
      "开好户再设置房租自动扣款与手机套餐。",
      {
        "type": "h2",
        "text": "地址证明怎么准备"
      },
      "若刚落地没有账单，可问银行是否接受学校信、租约或酒店证明等替代材料。",
      {
        "type": "image",
        "src": "/images/article-transport.png",
        "alt": "开户后的日常",
        "caption": "交通卡充值、超市支付都会轻松很多，尽早把账户用起来。"
      }
    ],
    "bodyEn": [
      "Common banks: ANZ, ASB, Westpac, BNZ. Bring passport, visa/entry, address and student proof.",
      "Book international-student appointments; some allow pre-arrival setup.",
      {
        "type": "image",
        "src": "/images/article-visa-docs.png",
        "alt": "Opening a bank account: the main banks",
        "caption": "Opening a bank account: the main banks"
      },
      "Ask about fees, transfers and card/app activation.",
      "IRD helps payroll later; never share codes/passwords.",
      "Then set rent autopay and phone plans.",
      {
        "type": "h2",
        "text": "Address evidence"
      },
      "Brand-new arrivals can ask whether a school letter, tenancy agreement or hotel proof is acceptable.",
      {
        "type": "image",
        "src": "/images/article-transport.png",
        "alt": "Everyday banking",
        "caption": "Transport top-ups and supermarket payments get easier once the account is live."
      }
    ]
  },
  {
    "slug": "supermarket-savings",
    "guideId": "life",
    "titleZh": "超市特价与省钱买菜",
    "titleEn": "Supermarket specials and saving on groceries",
    "excerptZh": "Pak'nSave、Countdown、New World 怎么搭配买更省。",
    "excerptEn": "How to combine Pak'nSave, Countdown and New World without overspending.",
    "image": "/images/hero-coast.png",
    "imageAltZh": "新西兰日常生活",
    "imageAltEn": "Everyday life in New Zealand",
    "bodyZh": [
      "三大连锁：Countdown（Woolworths）、New World、Pak'nSave。一周采购常去 Pak'nSave 更省。",
      "按 App/传单特价做菜单，比冲动买肉菜更省。",
      {
        "type": "image",
        "src": "/images/article-supermarket.png",
        "alt": "超市特价与省钱买菜",
        "caption": "超市特价与省钱买菜"
      },
      "积分卡看会员价；亚洲超市补米面调料。",
      "冷冻分装与临期折扣区适合控预算。",
      "开学季先备基础调料与早餐，减少天天外卖。",
      {
        "type": "h2",
        "text": "一周采购模板"
      },
      "主食 + 两种蛋白 + 当季蔬菜 + 乳品鸡蛋 + 水果。先定菜再进店，少拿购物车里的「顺便」。",
      {
        "type": "image",
        "src": "/images/article-supermarket.png",
        "alt": "蔬果区选购",
        "caption": "当季蔬菜通常更便宜也更新鲜，适合学生周菜单。"
      }
    ],
    "bodyEn": [
      "Countdown/Woolworths, New World and Pak'nSave—Pak'nSave often wins for weekly shops.",
      "Plan meals around specials.",
      {
        "type": "image",
        "src": "/images/article-supermarket.png",
        "alt": "Supermarket specials and saving on groceries",
        "caption": "Supermarket specials and saving on groceries"
      },
      "Use loyalty pricing; Asian grocers fill pantry gaps.",
      "Freeze portions; use markdown shelves wisely.",
      "Stock basics in week one to cut takeaways.",
      {
        "type": "h2",
        "text": "A simple weekly template"
      },
      "Staples + two proteins + seasonal veg + dairy/eggs + fruit. Decide meals before you shop.",
      {
        "type": "image",
        "src": "/images/article-supermarket.png",
        "alt": "Produce aisle",
        "caption": "Seasonal vegetables are usually cheaper and fresher for student menus."
      }
    ]
  },
  {
    "slug": "phone-sim-transport",
    "guideId": "life",
    "titleZh": "手机卡与公交怎么开通",
    "titleEn": "Getting a SIM and using public transport",
    "excerptZh": "落地先解决通讯与通勤，找房找工才方便。",
    "excerptEn": "Sort a SIM and transport early—housing and jobs get easier after that.",
    "image": "/images/hero-coast.png",
    "imageAltZh": "新西兰日常生活",
    "imageAltEn": "Everyday life in New Zealand",
    "bodyZh": [
      "常见运营商：Spark、One NZ、2degrees。机场或市区可办预付费，带护照即可。",
      "可先短周期预付费，稳定后再换长期计划。",
      {
        "type": "image",
        "src": "/images/article-transport.png",
        "alt": "手机卡与公交怎么开通",
        "caption": "手机卡与公交怎么开通"
      },
      "奥克兰用 AT HOP 等；其他城市有对应方式。学生折扣以当地交通局为准。",
      "用 Maps/公交 App 查班次；夜间周末可能更少。",
      "双因素认证确保能收短信或改用验证器。",
      {
        "type": "h2",
        "text": "第一周通勤建议"
      },
      "先搞清学校到住所的主干线路与末班时间；把交通卡与手机支付都设置好再密集看房。",
      {
        "type": "image",
        "src": "/images/article-arrival.png",
        "alt": "落地即连通",
        "caption": "通讯与交通是找房找工的基础设施，优先于添置家具。"
      }
    ],
    "bodyEn": [
      "Spark, One NZ, 2degrees are common; prepaid SIMs need your passport.",
      "Start prepaid short-term, switch later.",
      {
        "type": "image",
        "src": "/images/article-transport.png",
        "alt": "Getting a SIM and using public transport",
        "caption": "Getting a SIM and using public transport"
      },
      "Auckland uses AT HOP; other cities differ. Student discounts vary.",
      "Check live times; nights/weekends can be thinner.",
      "Keep 2FA working via SMS or an authenticator app.",
      {
        "type": "h2",
        "text": "Week-one commuting"
      },
      "Learn the main school–home route and last services before heavy flat hunting.",
      {
        "type": "image",
        "src": "/images/article-arrival.png",
        "alt": "Connected on arrival",
        "caption": "Phone and transport beat furniture shopping on the priority list."
      }
    ]
  },
  {
    "slug": "health-insurance-gp",
    "guideId": "life",
    "titleZh": "保险与看病：GP 怎么挂",
    "titleEn": "Insurance and seeing a GP",
    "excerptZh": "先搞清保险覆盖，再注册社区 GP；急诊只用于紧急情况。",
    "excerptEn": "Know your cover, enrol with a GP, and keep ED for emergencies.",
    "image": "/images/hero-coast.png",
    "imageAltZh": "新西兰日常生活",
    "imageAltEn": "Everyday life in New Zealand",
    "bodyZh": [
      "国际学生通常需要医疗保险；确认是否符合学校要求、门诊与处方自费多少。",
      "日常生病找社区 GP，问清是否接收新患者与预约方式。",
      {
        "type": "image",
        "src": "/images/article-visa-docs.png",
        "alt": "保险与看病：GP 怎么挂",
        "caption": "保险与看病：GP 怎么挂"
      },
      "急诊部用于急重症，不是普通感冒首选。",
      "处方在药房购买；保留收据备报销。",
      "心理健康可约学校 counseling，不必硬撑。",
      {
        "type": "h2",
        "text": "看病前准备"
      },
      "带保险卡/保单号、护照、症状与用药记录；问诊时说明过敏史。",
      {
        "type": "image",
        "src": "/images/article-shared-flat.png",
        "alt": "安稳生活节奏",
        "caption": "睡眠与压力管理也是「健康预算」的一部分，别只算药费。"
      }
    ],
    "bodyEn": [
      "Confirm insurance meets school rules and what you still pay.",
      "Enrol with a GP; ask about new patients and booking.",
      {
        "type": "image",
        "src": "/images/article-visa-docs.png",
        "alt": "Insurance and seeing a GP",
        "caption": "Insurance and seeing a GP"
      },
      "ED is for emergencies, not routine colds.",
      "Keep pharmacy receipts if your policy reimburses.",
      "Use campus counselling early when stress builds.",
      {
        "type": "h2",
        "text": "Before the appointment"
      },
      "Bring insurance details, passport, symptoms and medication list; mention allergies.",
      {
        "type": "image",
        "src": "/images/article-shared-flat.png",
        "alt": "Steady routines",
        "caption": "Sleep and stress management are part of the health budget too."
      }
    ]
  },
  {
    "slug": "arrival-first-week",
    "guideId": "life",
    "titleZh": "落地第一周清单",
    "titleEn": "Your first-week arrival checklist",
    "excerptZh": "住宿、手机、银行、交通、注册——按天推进不容易乱。",
    "excerptEn": "Housing, SIM, bank, transport, enrolment—day-by-day keeps it calm.",
    "image": "/images/hero-coast.png",
    "imageAltZh": "新西兰日常生活",
    "imageAltEn": "Everyday life in New Zealand",
    "bodyZh": [
      "第 1–2 天：入住短租/宿舍，买手机卡，确认 Wi-Fi 与紧急联系人。",
      "第 3–4 天：银行预约/开户，交通卡充值，熟悉超市与通勤。",
      {
        "type": "image",
        "src": "/images/article-arrival.png",
        "alt": "落地第一周清单",
        "caption": "落地第一周清单"
      },
      "第 5–6 天：学校注册、学生卡、Orientation，加入课程平台。",
      "第 7 天：备份护照/签证/offer/保险，列出长租、IRD、GP 待办。",
      "照顾时差，前几天别排太满；需要帮助就联系国际学生办公室或提交咨询。",
      {
        "type": "h2",
        "text": "文件备份怎么做"
      },
      "云盘 + 手机离线文件夹各一份；纸质复印件放随身与行李箱分开位置。",
      {
        "type": "image",
        "src": "/images/article-transport.png",
        "alt": "城市移动能力",
        "caption": "第一周目标不是完美安家，而是「通讯 + 交通 + 支付」跑通。"
      }
    ],
    "bodyEn": [
      "Days 1–2: short stay, SIM, Wi-Fi, emergency contacts.",
      "Days 3–4: bank, transport card, supermarket and commute.",
      {
        "type": "image",
        "src": "/images/article-arrival.png",
        "alt": "Your first-week arrival checklist",
        "caption": "Your first-week arrival checklist"
      },
      "Days 5–6: enrolment, ID, orientation, course platforms.",
      "Day 7: back up key files; list longer lease, IRD and GP tasks.",
      "Protect sleep; contact student support or use the consultation form if stuck.",
      {
        "type": "h2",
        "text": "Document backups"
      },
      "Cloud plus offline phone copies; keep paper copies in separate bags.",
      {
        "type": "image",
        "src": "/images/article-transport.png",
        "alt": "City mobility",
        "caption": "Week one success is phone + transport + payments working—not a perfect home setup."
      }
    ]
  }
];
