export const siteCopy = {
  zh: {
    siteName: "点点新西兰留学咨询",
    siteBrand: "点点",
    siteTag: "新西兰留学咨询",
    consultation: "咨询申请",
    heroTitle: "留学新西兰，从规划到落地",
    heroCta: "咨询申请",
    featuredLabel: "精选文章",
    backHome: "返回首页",
    backGuide: "返回指南",
    readArticle: "阅读文章",
    exploreGuide: "探索指南",
    authorTitle: "联系点点",
    authorBody:
      "2024 年来到新西兰，目前在 ICL 商学院就读。一边适应新环境，一边整理留学、求职与生活里踩过的坑和有用的经验。希望这个网站能给你真实、实用的参考；也欢迎你分享自己的故事，我们一起慢慢成长。",
  },
  en: {
    siteName: "DianDian NZ Study Consulting",
    siteBrand: "DianDian",
    siteTag: "NZ Study Consulting",
    consultation: "Consultation",
    heroTitle: "From plan to arrival in New Zealand.",
    heroCta: "Request a consultation",
    featuredLabel: "Featured",
    backHome: "Back to home",
    backGuide: "Back to guide",
    readArticle: "Read article",
    exploreGuide: "Explore guide",
    authorTitle: "Contact DianDian",
    authorBody:
      "I arrived in New Zealand in 2024 and am currently studying at ICL Business School. While settling in, I collect practical notes on study, work and daily life—what helped, and what I wish I had known sooner. I hope these pages are useful, and you are welcome to share your story too.",
  },
};

export const guides = [
  {
    id: "study",
    image: "/images/study-feature.png",
    imageAltZh: "新西兰私立学院与技能学校",
    imageAltEn: "A New Zealand private college campus",
    titleZh: "留学准备",
    titleEn: "Study preparation",
    summaryZh:
      "聚焦 AIS、ICL、Yoobee、NZSE、Future Skills 等私立/技能学校与学费区间，以及签证、语言、预算与申请节奏。",
    summaryEn:
      "Focus on AIS, ICL, Yoobee, NZSE and Future Skills-style private/skills providers with tuition ranges, plus visas, English, budget and timing.",
    introZh:
      "很多人问的不是八大排名，而是：奥克兰私立学院读什么、学费大概多少、PTE/语言班能不能衔接、商科 IT 酒店创意哪条路更贴自己。这里按 AIS、ICL、Yoobee、NZSE（NZSEG）、Future Skills 整理实用对照——讲清适合谁、学费大致区间，并提醒务必核对官网最新费用与 NZQA 级别。",
    introEn:
      "Many students need private/skills-provider options more than university rankings: what to study in Auckland colleges, typical tuition, PTE/English pathways, and which track fits—business, IT, hospitality or creative. These notes cover AIS, ICL, Yoobee, NZSE (NZSEG) and Future Skills with honest “who it suits” notes and approximate fee ranges—always verify current NZQA level and fees on the official site.",
    featuredSlug: "pte-private-schools",
    featuredTitleZh: "AIS / ICL / Yoobee / NZSE / Future Skills：学费与怎么选",
    featuredTitleEn: "AIS, ICL, Yoobee, NZSE, Future Skills: fees and who they suit",
  },
  {
    id: "career",
    image: "/images/career-feature.png",
    imageAltZh: "奥克兰城市天际线",
    imageAltEn: "The Auckland city skyline",
    titleZh: "求职与工作",
    titleEn: "Career and work",
    summaryZh:
      "Seek、Trade Me Jobs、简历、面试、IRD 与学生工时——本地找工刚需清单。",
    summaryEn:
      "Seek, Trade Me Jobs, CVs, interviews, IRD and student work hours—the essentials.",
    introZh:
      "本地兼职与全职大多从线上开始。Seek 岗位更全，Trade Me Jobs 本地感更强。下面把平台用法、简历、面试与合规工时一次讲清。",
    introEn:
      "Most local jobs start online. Seek is broader; Trade Me Jobs feels more local. Below: platforms, CVs, interviews and lawful work hours.",
    featuredSlug: "seek-trademe-jobs",
    featuredTitleZh: "在 Seek 与 Trade Me 找工作：实用建议",
    featuredTitleEn: "Finding work on Seek and Trade Me: practical tips",
  },
  {
    id: "life",
    image: "/images/hero-coast.png",
    imageAltZh: "新西兰海岸与城市生活",
    imageAltEn: "New Zealand coast and everyday life",
    titleZh: "生活指南",
    titleEn: "Living in NZ",
    summaryZh: "月度生活费预算、租房、开户、超市省钱、手机公交、保险看病与落地第一周。",
    summaryEn:
      "Monthly living budget, renting, banking, supermarket savings, SIM/transport, insurance and your first week.",
    introZh:
      "落地后最先卡住的往往不是课程，而是租房、银行卡、手机卡和看病。这一区按刚需顺序整理，帮你少花冤枉钱、少踩坑。",
    introEn:
      "After arrival, housing, banking, a SIM and healthcare usually come before coursework. This guide follows that essential order.",
    featuredSlug: "nz-monthly-budget",
    featuredTitleZh: "留学生一个月生活费怎么算",
    featuredTitleEn: "A practical one-month NZ living budget",
  },
];

export const articles = [
  {
    slug: "pte-private-schools",
    guideId: "study",
    titleZh: "AIS / ICL / Yoobee / NZSE / Future Skills：学费与怎么选",
    titleEn: "AIS, ICL, Yoobee, NZSE, Future Skills: fees and who they suit",
    excerptZh:
      "私立与技能学校常见短名单：城市、专业方向、大致学费（纽币）与适合谁——费用以官网为准。",
    excerptEn:
      "A practical private/skills shortlist: city, typical programmes, approximate NZD fees, and who each suits—verify on official sites.",
    image: "/images/study-feature.png",
    imageAltZh: "新西兰私立学院与技能学校",
    imageAltEn: "A New Zealand private college campus",
    bodyZh: [
      "先说清楚：本文不是八大/大学排名清单，而是很多中国学生实际会问的私立培训机构（Private Training Establishment）与技能/应用型学院路径。学费会随学年、专业、奖学金与地区促销变动；数字为近年公开材料中的大致区间（纽币 NZD），报名前务必核对官网。",
      "怎么筛：① NZQA 级别与课程时长（证书/文凭/本科/研文/硕士差别很大）；② 英语是 IELTS、PTE Academic 还是 NZCEL/语言班；③ 专业是否匹配目标；④ 奥克兰房租会显著拉高总成本；⑤ 别把「好录取」当成「好就业」或「好移民」。",
      "本指南为每所学校准备了独立详解：AIS、ICL、Yoobee、NZSE（NZSEG）、Future Skills。下面是快速对照，点进留学准备指南可打开各校专文。",
      "AIS——奥克兰，应用型商科/IT/酒店与语言衔接；文凭/研文常见约 NZD 22,000–27,000，本科约 NZD 22,000–24,000/年，部分硕士约 NZD 40,000 量级。",
      "ICL——奥克兰 CBD 商学院路径（站长就读）；Level 5 到 Level 9 国际生常见约 NZD 23,000–48,500，另有报名与材料费，促销价以 Offer 为准。",
      "Yoobee——创意与数字（动画、设计、软件）；文凭/本科常见约 NZD 27,300，另收资源/行政费。",
      "NZSE / NZSEG——技能就业导向（IT、商务、数据分析、教学等）；不同课差价大，约 NZD 18,900–35,500+。若见「NESEG」多半是 NZSEG 误写。",
      "Future Skills——奥克兰 Queen Street；应用管理/建筑相关与部分硕士；标价例约 NZD 23,900–40,500，常有奖学金后净价。",
      "专业对号：商科/管理 → ICL、AIS、Future Skills、NZSE；IT/软件 → Yoobee、AIS、NZSE、Future Skills；酒店旅游 → AIS、ICL；创意动画 → Yoobee。需要 2–3 所短名单时，可提交咨询申请。",
    ],
    bodyEn: [
      "This is not an “eight universities” list. It covers PTE/skills providers many Chinese students actually ask about. Fees change by year, programme and promo—figures are approximate NZD; verify on official sites.",
      "Filter by NZQA level and length, English pathway, subject fit, Auckland rent, and realistic outcomes—not just easy entry.",
      "Each school has its own deep-dive article: AIS, ICL, Yoobee, NZSE (NZSEG) and Future Skills. Open the Study preparation guide to read them.",
      "AIS—Auckland applied business/IT/hospitality with language bridging; diplomas/PGDips often ~NZD 22k–27k, bachelor ~NZD 22k–24k/year, some master’s ~NZD 40k.",
      "ICL—Auckland CBD business pathway (site author studies here); international fees often ~NZD 23k–48.5k by level, plus enrolment/materials; use your offer for promos.",
      "Yoobee—creative/digital (animation, design, software); diplomas/bachelor years often ~NZD 27,300 plus resource fees.",
      "NZSE/NZSEG—skills-to-work (IT, business, analytics, teaching); wide fee spread ~NZD 18.9k–35.5k+. “NESEG” is usually a misspelling of NZSEG.",
      "Future Skills—Queen Street Auckland; applied management/construction-related and some master’s; list prices ~NZD 23.9k–40.5k, scholarships often change the net fee.",
      "Subject mapping: business → ICL, AIS, Future Skills, NZSE; IT/software → Yoobee, AIS, NZSE, Future Skills; hospitality → AIS, ICL; creative → Yoobee. Use the consultation form for a 2–3 school shortlist.",
    ],
  },
  {
    slug: "school-ais",
    guideId: "study",
    titleZh: "AIS 奥克兰商学院：专业、学费与适合谁",
    titleEn: "AIS Auckland: programmes, fees and who it suits",
    excerptZh: "Auckland Institute of Studies：商科、IT、酒店与语言衔接的实用对照。",
    excerptEn:
      "Auckland Institute of Studies: business, IT, hospitality and English pathways.",
    image: "/images/study-feature.png",
    imageAltZh: "AIS 奥克兰私立学院",
    imageAltEn: "AIS Auckland private college",
    website: "https://ais.ac.nz/",
    bodyZh: [
      "AIS（Auckland Institute of Studies）是奥克兰常见的私立培训机构（PTE）。中文资料里有时写成「奥克兰商学院」等，名称不统一——选校、交费、签证材料一律以官网与 NZQA 注册全名为准：https://ais.ac.nz/",
      "适合谁：想在奥克兰读应用型商科、IT、酒店管理，或需要 NZCEL/语言班再衔接主课的人；也适合把文凭/研文当作较短升学路径、同时对照预算的人。若你的目标是综合大学研究型硕士或「八大名校」叙事，AIS 通常不是同一条赛道。",
      "常见方向：商务与管理类文凭/本科、IT 相关课程、酒店与旅游管理、英语（含 NZCEL）以及部分研文与硕士（如 MBA、Master of IT 一类——以当季课程页为准）。同一学校不同课的 NZQA 级别、时长与英语要求差很多，短名单前务必点开具体 programme。",
      "学费大致区间（国际生、纽币，近年公开材料，约数）：一年制文凭/研文常见约 NZD 22,000–27,000；本科常见约 NZD 22,000–24,000/年；MBA / Master of IT 一类硕士常见约 NZD 40,000 量级（有的按整课、有的按年公布）。另计报名费、材料费、保险与生活费。促销与奖学金会变，以 Offer / 官网学费页为准。",
      "英语与衔接：多数主课接受 IELTS Academic 或 PTE Academic；分数不够时常见路径是语言班或 NZCEL 再升主课。别只听口头「过了就能读」——把目标课的 English requirements 截图存档。",
      "预算提醒：AIS 主战场在奥克兰，房租往往比学费差额更「伤」。把「一年学费 + 一年合租/单间」放进同一张表，再和 ICL、Future Skills 等同城选项比。",
      "申请前核对：① NZQA 批准与课程级别；② 开学季与时长；③ 学费是按年还是整课；④ Conditional Offer 条件（语言、材料、押金日期）。需要和别的学校做 2–3 所对照时，可用首页咨询表整理背景。",
    ],
    bodyEn: [
      "AIS (Auckland Institute of Studies) is a commonly discussed Auckland PTE. Official site: https://ais.ac.nz/. Chinese nicknames vary—always use the official/NZQA name for applications, payments and visas.",
      "Who it suits: applied business, IT or hospitality in Auckland, or students who need NZCEL/pathway English before a main programme. If you want a research university master’s or an “eight universities” path, AIS is a different track.",
      "Typical areas: business/management diplomas and bachelor’s, IT-related study, hospitality/tourism, English including NZCEL, plus some graduate diplomas and master’s (e.g. MBA / Master of IT—confirm current pages). Levels, length and English rules differ by programme.",
      "Approximate international fees (recent public materials, NZD): diploma/graduate-diploma years often ~22,000–27,000; bachelor years ~22,000–24,000; MBA / Master of IT-type study often around ~40,000 (check year vs full-programme pricing). Add enrolment, materials, insurance and living costs; promos change—use your offer.",
      "English: IELTS Academic or PTE Academic is common; pathway English or NZCEL may bridge into the main course. Save the official English requirements for your exact programme.",
      "Budget note: Auckland rent can outweigh tuition gaps. Compare one year of fees plus shared/private rent against peers such as ICL and Future Skills.",
      "Before you apply: NZQA approval and level, intake and duration, fee structure, and conditional-offer terms. Use the consultation form to compare 2–3 options against your budget and background.",
    ],
  },
  {
    slug: "school-icl",
    guideId: "study",
    titleZh: "ICL 商学院：课程路径、学费与就读体验要点",
    titleEn: "ICL Business School: pathways, fees and practical notes",
    excerptZh: "奥克兰 CBD 的 ICL：商科管理、信息化与研文/硕士路径怎么看。",
    excerptEn:
      "ICL in Auckland CBD: business, informatics and graduate pathways explained.",
    image: "/images/study-feature.png",
    imageAltZh: "ICL 奥克兰 CBD 商学院",
    imageAltEn: "ICL Auckland CBD business school",
    website: "https://icl.ac.nz/",
    bodyZh: [
      "ICL（ICL Graduate Business School / ICL Education）位于奥克兰 CBD，是站长目前就读的商学院路径。官网：https://icl.ac.nz/。选校材料里请核对官方名称与 NZQA 注册信息，不要只记中介口头简称。",
      "适合谁：希望在市中心读应用型商科/管理、商业信息、酒店旅游相关研文，或 ECE 幼教类研文，并接受「较短、偏实务」升学节奏的人。若你要的是大型综合大学校园生活或强研究型导师制，ICL 的体验会不一样。",
      "常见课程类型：商务文凭（Level 5 等）、管理/信息化相关研文与硕士方向、酒店与旅游相关研究生课程、ECE 教学研文等。开学季与班型会变，以官网课程页与招生办回复为准。",
      "学费大致区间（国际生、2025–2026 公开表常见）：约 NZD 23,000–48,500，视 Level 5 文凭到 Level 9 硕士而定。另有报名费（公开材料常见约 NZD 260）与教材/材料费。地区促销价很常见——口头优惠不算数，以录取通知书与缴费说明为准。",
      "英语要求：多数课程接受 IELTS / PTE；不够分时询问当季语言衔接或条件录取规则。交押金前把「主课开课条件」写成清单：语言、材料、缴费截止日期。",
      "生活与通勤：CBD 上课方便兼职与实习奔波，但房租与餐饮通常更贵。算预算时把交通卡、合租押金、首月生活费单独列。",
      "实用建议：① 先定级别（文凭 vs 研文 vs 硕士），再比学费；② 同一方向保留 AIS 或 Future Skills 作备选；③ 签证材料按移民局清单准备，不要默认「学校代办就不用自己核对」。背景复杂或要缩短名单时，可用咨询表整理学历、工作与资金情况。",
    ],
    bodyEn: [
      "ICL (ICL Graduate Business School / ICL Education) sits in Auckland CBD—the pathway the site author currently studies. Official site: https://icl.ac.nz/. Confirm the official NZQA-registered name; do not rely on informal agent nicknames alone.",
      "Who it suits: applied business/management, business informatics, hospitality/tourism graduate study, or ECE teaching graduate diplomas with a practical, often shorter cadence. It is not the same experience as a large research university campus.",
      "Common types: business diplomas (e.g. Level 5), management/informatics graduate and master’s streams, hospitality/tourism postgraduate options, ECE teaching graduate diplomas. Intakes change—use the current programme pages.",
      "Approximate international fees (2025–2026 public schedules): often about NZD 23,000–48,500 from Level 5 diplomas to Level 9 master’s, plus enrolment (often ~NZD 260 in public materials) and materials. Regional promotions are common—only your offer letter counts.",
      "English: IELTS/PTE is typical; ask about pathway or conditional rules if scores are short. Before paying a deposit, list start conditions: English, documents and payment deadlines.",
      "Living costs: CBD helps with commuting to part-time work, but rent and food are usually higher. Budget transport, bond and first-month living costs separately.",
      "Practical tips: lock the level first (diploma vs PGDip vs master’s), keep AIS or Future Skills as a backup, and prepare visa evidence yourself even if an agent helps. Use the consultation form when your background or budget needs a tighter shortlist.",
    ],
  },
  {
    slug: "school-yoobee",
    guideId: "study",
    titleZh: "Yoobee：动画、设计与软件课程怎么选",
    titleEn: "Yoobee: animation, design and software programmes",
    excerptZh: "创意与数字技术导向：作品集、校区与大致学费。",
    excerptEn:
      "Creative and digital tech pathways: portfolios, campuses and fee ranges.",
    image: "/images/study-feature.png",
    imageAltZh: "Yoobee 创意与数字学院",
    imageAltEn: "Yoobee creative and digital college",
    website: "https://yoobee.ac.nz/",
    bodyZh: [
      "Yoobee（Yoobee Colleges / Yoobee College of Creative Innovation）以创意与数字技术见长，校区常见于奥克兰、惠灵顿、基督城等。官网：https://yoobee.ac.nz/。它更像「作品集 + 技能输出」路线，而不是综合大学人文社科叙事。",
      "适合谁：目标明确在动画、数字媒体/设计、软件开发或软件工程，愿意持续做作品集、项目展示的人。若你主要想读通用商科管理硕士，通常应优先对照 ICL、AIS、Future Skills，而不是硬塞进 Yoobee。",
      "常见方向：创意基础证书、数字媒体/设计类文凭、动画相关课程、软件开发/软件工程文凭或本科等。具体 NZQA 级别与时长以官网为准；同一「设计」标题下，课表与设备要求可能差很多。",
      "学费大致区间（国际生、2026 公开价例）：创意基础证书约 NZD 15,000 量级；多数文凭约 NZD 27,300；本科常见约 NZD 27,300/年；另收资源/行政费约 NZD 1,400–2,400。软件与硬件要求高的课，材料/设备开销要单独问清。",
      "申请重点：作品集质量往往比「只看分数」更关键。提早按课程页要求整理项目（过程稿、最终稿、工具说明）；英语成绩仍要满足官方线（IELTS/PTE 等）。",
      "城市选择：奥克兰机会多但房租高；惠灵顿、基督城可能生活费更友好，但兼职市场与行业社群不同。选校区时把「课表城市」和「你能住得起的城市」写成同一决策。",
      "避坑：确认课程是否仍在招国际生、开学季是否对得上签证节奏；不要只看宣传片设备。需要和 NZSE/AIS 的 IT 路径对比时，可把作品集导向 vs 技能就业导向写进咨询表备注。",
    ],
    bodyEn: [
      "Yoobee (Yoobee Colleges / College of Creative Innovation) focuses on creative and digital technology, with campuses commonly in Auckland, Wellington and Christchurch. Official site: https://yoobee.ac.nz/. Think portfolio-and-skills output, not a generic university arts narrative.",
      "Who it suits: animation, digital media/design, software development or software engineering students who will keep building a portfolio. For a general business/management master’s, compare ICL, AIS or Future Skills first.",
      "Typical areas: creative foundation certificates, digital media/design diplomas, animation-related study, software development/engineering diplomas or bachelor’s. Check NZQA level and length per programme—titles can hide very different workloads.",
      "Approximate international fees (2026 public examples): creative foundation certificates around NZD 15,000; many diplomas around NZD 27,300; bachelor years often ~NZD 27,300 plus resource/admin fees ~NZD 1,400–2,400. Ask about equipment costs for software/hardware-heavy courses.",
      "Applications: portfolio quality often matters as much as scores. Prepare projects to the brief (process, finals, tools). English still must meet official IELTS/PTE (or equivalent) rules.",
      "City choice: Auckland has more opportunities but higher rent; Wellington/Christchurch may be cheaper to live in with different job markets. Tie campus city to a rent you can actually afford.",
      "Caveats: confirm international intakes and visa timing; do not choose only from promo videos. When comparing with NZSE/AIS IT paths, note portfolio-led vs skills-to-work goals in the consultation form.",
    ],
  },
  {
    slug: "school-nzse",
    guideId: "study",
    titleZh: "NZSE / NZSEG：技能课程、校区与学费区间",
    titleEn: "NZSE / NZSEG: skills programmes, campuses and fees",
    excerptZh: "IT、商务、数据分析与教学类路径；认准 NZSEG，别被 NESEG 误导。",
    excerptEn:
      "IT, business, analytics and teaching paths—confirm NZSEG, not “NESEG”.",
    image: "/images/study-feature.png",
    imageAltZh: "NZSE 技能与教育学院",
    imageAltEn: "NZSE skills and education college",
    website: "https://nzse.ac.nz/",
    bodyZh: [
      "NZSE（New Zealand Skills and Education College）隶属 NZSEG（New Zealand Skills and Education Group）。官网：https://nzse.ac.nz/（集团信息可对照 https://nzseg.com/）。若中介材料写「NESEG」，多数是 NZSEG 的误写/口误；也有中文资料写成 New Zealand School of Education——请以 NZQA 注册名核对后再交钱。",
      "适合谁：更看重技能就业、希望课程偏实务（IT 技术支持、网络云、商务、数据分析、工程或教学/幼教相关）的人。它和 Yoobee 的创意作品集路线、ICL 的 CBD 商科硕士路径，决策逻辑不同。",
      "校区：常见讨论包括奥克兰 CBD、New Lynn、Manukau 以及怀卡托等。同一集团不同校区的开课表可能不同——报名时确认「你上的那门课」在哪个 campus。",
      "学费公开价例（国际生、约数，不同课差很大）：IT Technical Support（Level 5）约 NZD 20,000；部分 IT/网络云相关 Level 7 约 NZD 20,000；数据分析研文约 NZD 18,900；教学类研文可到约 NZD 35,500；个别商务文凭标价更高（有页面见约 NZD 38,000）。务必按具体 programme 下载最新国际生学费表。",
      "英语与入学：常见 IELTS/PTE 要求，部分路径可能有学术或工作背景要求。教学类课程往往还有额外条件（背景调查、实习安排等）——提早问清，避免 Offer 后来不及准备。",
      "怎么和其它学校对照：偏软件作品集 → 看 Yoobee；偏应用管理/奖学金净价 → 对照 Future Skills；偏 CBD 商科硕士体验 → 对照 ICL；偏商科/酒店综合应用 → 对照 AIS。",
      "行动清单：核对 NZQA 名称 → 选定校区与级别 → 拉齐学费+奥克兰/当地房租 → 确认英语与实习/工签相关规则。需要顾问帮你排除「听起来像、其实不是同一所」的校名时，把中介材料截图备注进咨询表。",
    ],
    bodyEn: [
      "NZSE (New Zealand Skills and Education College) sits under NZSEG (New Zealand Skills and Education Group). Official site: https://nzse.ac.nz/ (group: https://nzseg.com/). “NESEG” is usually a misspelling; some Chinese materials say “New Zealand School of Education”—confirm the NZQA-registered name before you pay.",
      "Who it suits: skills-to-work goals in IT support, network/cloud, business, data analytics, engineering or teaching/ECE-related study. That is a different decision from Yoobee’s portfolio creative track or ICL’s CBD business master’s path.",
      "Campuses often discussed: Auckland CBD, New Lynn, Manukau and Waikato. Timetables can differ by campus—confirm where your exact programme runs.",
      "Public international fee examples (approximate; wide spread): IT Technical Support (Level 5) ~NZD 20,000; some Level 7 network/cloud diplomas ~NZD 20,000; graduate diploma in data analytics ~NZD 18,900; teaching graduate diplomas can reach ~NZD 35,500; some business diplomas list higher (~NZD 38,000 on some pages). Download the latest fee schedule for your programme.",
      "Entry: IELTS/PTE is common; some paths need academic or work background. Teaching programmes may add checks or placement requirements—ask early.",
      "Compare: portfolio software/creative → Yoobee; scholarship-sensitive applied management → Future Skills; CBD business master’s experience → ICL; broader applied business/hospitality → AIS.",
      "Checklist: NZQA name → campus and level → fees plus local rent → English and any placement/visa-related rules. If agent paperwork uses confusing names, attach notes in the consultation form.",
    ],
  },
  {
    slug: "school-future-skills",
    guideId: "study",
    titleZh: "Future Skills：应用管理、学费与奖学金怎么看",
    titleEn: "Future Skills: applied management, fees and scholarships",
    excerptZh: "Queen Street 国际校区：本科/研文/硕士标价与奖学金净价。",
    excerptEn:
      "Queen Street campus: bachelor/PGDip/master’s list prices vs scholarship net fees.",
    image: "/images/study-feature.png",
    imageAltZh: "Future Skills 奥克兰国际校区",
    imageAltEn: "Future Skills Auckland international campus",
    website: "https://www.futureskills.co.nz/",
    bodyZh: [
      "Future Skills（Future Skills Academy）国际生常讨论的是奥克兰 Queen Street 国际校区路径。官网：https://www.futureskills.co.nz/。宣传里会出现应用管理、建筑/工料测量相关，以及 AI/IT 整合类硕博说法——一律以官网当季课程与 NZQA 批准为准，不要只看中介海报。",
      "适合谁：想在奥克兰市中心读应用管理本科/研文/硕士，或建筑相关应用课，并且会认真算「标价 vs 奖学金后净学费」的人。若你的核心是动画作品集，优先看 Yoobee；若是技能 IT 支持就业课，对照 NZSE。",
      "常见方向：Bachelor of Applied Management、应用管理研文/硕士、建筑或工料测量相关课程，以及部分 AI/IT 整合硕博宣传项目。级别（本科 / PGDip / Master）决定学费结构与签证相关讨论起点，先锁定级别再比学校。",
      "学费公开「标价」例（国际生、2026 材料常见）：Bachelor of Applied Management 约 NZD 23,900/年；研文约 NZD 27,000；部分硕士整课约 NZD 40,500。学校常有奖学金或促销后价格——关键是：奖学金条款、是否自动、是否绑定国籍/开学季、失败重修是否还能享受。最终以 Offer 与缴费通知为准。",
      "英语与材料：按课程页准备 IELTS/PTE（或认可等效）；申请硕士/研文时常见本科学历与成绩要求。收到 Conditional Offer 后，把条件逐条写成日期表。",
      "成本对照：把 Future Skills 的「奖学金后净价」和 ICL、AIS 的「常见成交价/促销价」放在同一张表，同时加上 Queen Street 一带房租预期。只比较标价，很容易误判。",
      "下一步：下载最新国际生学费与奖学金页 → 选定 1 个主申级别 → 再选 ICL 或 AIS 作备选 → 用咨询表填写学历、预算与开学目标，便于压缩短名单。",
    ],
    bodyEn: [
      "Future Skills (Future Skills Academy) international discussions often centre on the Auckland Queen Street campus. Official site: https://www.futureskills.co.nz/. Marketing may mention applied management, construction/quantity-surveying related study, and AI/IT-integrated postgraduate options—always verify current NZQA-approved programmes on the official site.",
      "Who it suits: students targeting applied management (bachelor/PGDip/master’s) or construction-related applied study in central Auckland, and who will calculate list price versus scholarship net fees. For animation portfolios, prefer Yoobee; for skills IT support, compare NZSE.",
      "Typical areas: Bachelor of Applied Management, applied management PGDip/master’s, construction/QS-related courses, and some AI/IT-integrated postgraduate marketing. Lock the level before comparing schools.",
      "Public list-price examples (international, 2026 materials): Bachelor of Applied Management ~NZD 23,900/year; PGDip ~NZD 27,000; some master’s packages ~NZD 40,500. Scholarships/promos are common—read eligibility, intake limits and what happens if you repeat a paper. Your offer is the source of truth.",
      "English and documents: follow the programme page for IELTS/PTE (or accepted equivalents); postgraduate study usually needs a relevant bachelor background. Turn conditional-offer terms into a dated checklist.",
      "Cost comparison: put Future Skills scholarship-adjusted fees next to typical ICL/AIS offer pricing, plus Queen Street-area rent. Comparing list prices alone misleads.",
      "Next steps: download current fees/scholarship pages → choose one primary level → keep ICL or AIS as backup → use the consultation form with education, budget and intake goals.",
    ],
  },
  {
    slug: "nz-private-providers",
    guideId: "study",
    titleZh: "五所私立/技能学校怎么对照短名单",
    titleEn: "Comparing five private/skills providers for a shortlist",
    excerptZh: "先定专业与预算，再在 AIS、ICL、Yoobee、NZSE、Future Skills 里做 2–3 所组合。",
    excerptEn:
      "Lock subject and budget first, then pick 2–3 from AIS, ICL, Yoobee, NZSE and Future Skills.",
    image: "/images/study-feature.png",
    imageAltZh: "新西兰私立学院与技能学校",
    imageAltEn: "A New Zealand private college campus",
    bodyZh: [
      "短名单别从「名气」起，从三件事起：专业方向、可接受学费上限（含一年奥克兰房租）、英语现状（能否直入 / 需要 NZCEL 或语言班）。总览见《学费与怎么选》；各校细节见 AIS / ICL / Yoobee / NZSE / Future Skills 独立文章。",
      "偏商科管理、想读研文/硕士且希望在奥克兰 CBD：优先对照 ICL 与 Future Skills，AIS 作应用型本科/研文备选。",
      "偏 IT 技术支持、网络云、数据分析就业课：对照 NZSE 与 AIS；软件/数字作品集路线看 Yoobee；AI/IT 硕可看 Future Skills 当季项目。",
      "偏酒店、旅游、商务实践课：AIS 与 ICL 相关文凭/研文更常进入讨论；创意动画设计几乎总是 Yoobee 优先。",
      "操作建议：每方向保留 1 所主申 + 1 所备选；打开各校专文核对学费与适合谁，再下载官网最新国际生学费表，把「标价 / 促销价 / 材料费」写进同一张表。",
    ],
    bodyEn: [
      "Start a shortlist from subject, max tuition (plus Auckland rent), and English readiness—not brand names. Use the overview article plus each school’s deep-dive (AIS, ICL, Yoobee, NZSE, Future Skills).",
      "Business/management with graduate diploma or master’s in Auckland CBD: compare ICL and Future Skills first; keep AIS as an applied bachelor/graduate option.",
      "IT support, network/cloud, analytics-to-work: compare NZSE and AIS; portfolio software/digital paths → Yoobee; AI/IT master’s → check current Future Skills programmes.",
      "Hospitality/tourism/applied business: AIS and ICL pathways come up most; creative animation/design almost always starts with Yoobee.",
      "Process: one primary + one backup per direction; read each school article, then line up official list price / promo / materials before you commit.",
    ],
  },
  {
    slug: "nz-application-timeline",
    guideId: "study",
    titleZh: "新西兰留学申请时间线（附清单）",
    titleEn: "A New Zealand application timeline and checklist",
    excerptZh: "从定专业到拿 offer、办签证，按月份倒推更不容易漏项。",
    excerptEn:
      "Work backwards from intake to offers and visas so fewer items slip.",
    image: "/images/study-feature.png",
    imageAltZh: "新西兰大学校园",
    imageAltEn: "A New Zealand university campus",
    bodyZh: [
      "申请不是从填表开始，而是从时间倒推开始。先确定目标开学季（常见 2 月 / 7 月），再往前排语言考试、材料、申请与签证。",
      "开学前 9–12 个月：确定专业与 3–5 所学校短名单；准备成绩单、毕业证明/在读证明；规划雅思/PTE 考试时间。",
      "开学前 6–9 个月：提交网申，准备个人陈述、简历、推荐信或作品集（视专业而定）；跟进补件邮件，别让申请停在 incomplete。",
      "开学前 3–6 个月：比较 offer 条件（语言、预科、押金截止日期）；接受 offer 并缴费；启动学生签证材料（资金、保险、录取文件等，以移民局要求为准）。",
      "开学前 1–2 个月：安排住宿、接机、银行卡与手机卡；核对课程注册与 Orientation 时间；把重要文件电子版与纸质版各留一份。",
      "简易清单：护照有效期、成绩单、语言成绩、录取/COE、资金证明、保险、住址与紧急联系人。每完成一项就打勾，比临出发前赶材料轻松很多。",
    ],
    bodyEn: [
      "Applications start with a calendar, not a form. Lock your intake (often February or July), then work backwards through English tests, documents, offers and visa timing.",
      "9–12 months out: shortlist 3–5 programmes; prepare transcripts and enrolment/graduation evidence; book IELTS/PTE.",
      "6–9 months out: submit applications; draft statement, CV, references or portfolio as required; answer incomplete-document emails quickly.",
      "3–6 months out: compare offer conditions, accept and pay deposits, then start the student visa file using Immigration NZ’s current checklist.",
      "1–2 months out: arrange housing, arrival, banking and a local SIM; confirm enrolment and orientation; keep digital and paper copies of key documents.",
      "Simple checklist: valid passport, transcripts, English score, offer/COE, funds evidence, insurance, address and emergency contact. Tick items as you go.",
    ],
  },
  {
    slug: "student-visa-basics",
    guideId: "study",
    titleZh: "学生签证材料与常见卡点",
    titleEn: "Student visa documents and common blockers",
    excerptZh: "资金、录取、保险与行程说明——按移民局清单准备，别凭经验猜测。",
    excerptEn:
      "Funds, offer, insurance and travel plans—follow Immigration NZ, not guesswork.",
    image: "/images/study-feature.png",
    imageAltZh: "新西兰大学校园",
    imageAltEn: "A New Zealand university campus",
    bodyZh: [
      "学生签证以 Immigration New Zealand 当前要求为准。核心通常包括：有效护照、录取/缴费证明、资金证明、保险安排，以及真实的学习计划说明。",
      "资金证明要「说得通」：存款时长、资金来源、学费+生活费是否覆盖。临时大额转入又说不清来源，是常见补件原因。",
      "收到 Conditional Offer 先分清条件：语言、成绩单原件、押金等。条件未完成就递签，容易反复。",
      "保险：很多学校要求注册前已有合适医疗保险。买之前核对保障范围与入学要求。",
      "递交后保持邮箱与 Immigrate 账户畅通，补件尽量一次给齐。政策会变，临交前再核对官网。",
    ],
    bodyEn: [
      "Always follow the current Immigration NZ checklist. Core items usually include passport, offer/fee evidence, funds, insurance and a credible study plan.",
      "Funds must make sense: history, source, and coverage of tuition plus living costs. Unexplained sudden large deposits often trigger requests for more information.",
      "With a conditional offer, separate language, document and deposit conditions. Applying before conditions are met causes delays.",
      "Insurance: many schools require suitable medical cover before enrolment—match policy scope to school rules.",
      "Keep email and your immigration account monitored; answer requests completely. Recheck the official site before you submit.",
    ],
  },
  {
    slug: "english-test-guide",
    guideId: "study",
    titleZh: "雅思与 PTE：分数怎么够用",
    titleEn: "IELTS and PTE: scores that actually work",
    excerptZh: "先查课程官网英语要求，再选考试；PTE 与雅思都要看总分和小分。",
    excerptEn:
      "Check the course page first, then choose a test—overall and skill scores both matter.",
    image: "/images/study-feature.png",
    imageAltZh: "新西兰大学校园",
    imageAltEn: "A New Zealand university campus",
    bodyZh: [
      "私立学院与技能学校（如 AIS、ICL、Yoobee、NZSE、Future Skills）多数接受 IELTS Academic 或 PTE Academic，分数线因课程级别而异；也常见 NZCEL 或语言班衔接。以课程页 English language requirements 为准，不要只看中介口头标准。",
      "备考策略：先模考定位弱项（写作/口语常见）。时间紧的人可比较近期考位与出分速度，再决定雅思或 PTE。",
      "差 0.5 分时：看是否接受语言班、NZCEL、内部语言测试或有条件录取，别盲目重考耽误开学季。",
      "材料同步：成绩单公证/翻译与语言成绩并行准备，避免语言过了却卡在成绩单。",
      "到校后仍要持续练学术写作与课堂讨论——入学分只是门槛，不是课业终点。",
    ],
    bodyEn: [
      "Private/skills providers (e.g. AIS, ICL, Yoobee, NZSE, Future Skills) usually accept IELTS Academic or PTE Academic, with cut-offs by programme level; NZCEL or pathway English is also common. Use the official English requirements page—not verbal summaries.",
      "Prep: mock-test first to find weak skills (writing/speaking are common). If time is tight, compare test dates and result speed before choosing IELTS or PTE.",
      "If you miss by a small margin, check pathway English, NZCEL, internal tests or conditional offers before delaying an intake with another attempt.",
      "Run transcript notarisation/translation in parallel so documents are not the new bottleneck after you pass English.",
      "After arrival, keep building academic writing and discussion skills—entry scores are a gate, not the finish line.",
    ],
  },
  {
    slug: "offer-acceptance-checklist",
    guideId: "study",
    titleZh: "拿到 Offer 后做什么（清单）",
    titleEn: "Got an offer? Next-step checklist",
    excerptZh: "分清条件、缴费、接受 offer、签证与住宿——按顺序推进。",
    excerptEn:
      "Conditions, fees, acceptance, visa and housing—move in order.",
    image: "/images/study-feature.png",
    imageAltZh: "新西兰大学校园",
    imageAltEn: "A New Zealand university campus",
    bodyZh: [
      "先把 Offer 读完：课程名、开学日、学费、条件（语言/材料/押金截止日期）。截图或下载 PDF 存档。",
      "多份 Offer 时对比：总时长、是否含实习、城市房租、语言条件能否在截止日期前完成。",
      "接受 Offer 与缴费按学校说明操作，保留收据。需要 COE/缴费证明递签的，确认文件是否已生成。",
      "同步启动：签证材料、保险、住宿意向（先短租也行）、机票灵活日期。",
      "入学前再核：注册、Orientation、学生账号与邮箱。有问题尽早写国际学生办公室，别等开学当周。",
    ],
    bodyEn: [
      "Read the offer fully: programme name, start date, fees and conditions (English/documents/deposit deadlines). Save the PDF.",
      "If you hold multiple offers, compare duration, placements, city rent and whether language conditions are realistic before the deadline.",
      "Accept and pay exactly as instructed; keep receipts. Confirm COE/payment letters needed for the visa.",
      "Start in parallel: visa file, insurance, housing (short stay is fine first) and flexible flights.",
      "Before arrival: enrolment, orientation, student login and email. Contact international student support early—not in week one.",
    ],
  },
  {
    slug: "tuition-living-budget",
    guideId: "study",
    titleZh: "学费与生活费：怎么做年度预算",
    titleEn: "Tuition and living costs: a yearly budget",
    excerptZh: "把学费、房租、交通、保险分项算清，奥克兰与其他城市差很多。",
    excerptEn:
      "Split tuition, rent, transport and insurance—Auckland differs a lot from other cities.",
    image: "/images/study-feature.png",
    imageAltZh: "新西兰大学校园",
    imageAltEn: "A New Zealand university campus",
    bodyZh: [
      "预算至少分五块：学费、房租、日常饮食、交通通讯、保险杂费。私立学院按实际月数与课程级别估算，不要只抄「一年生活费」笼统数字；材料费、报名费也要单独列。",
      "房租是最大变量：本文主推的 AIS / ICL / Yoobee / NZSE / Future Skills 多在奥克兰，单间/合租会显著拉高总成本——选校时把「学费差」和「房租」一起算。",
      "打工收入别写进「必须依赖」的预算里——工时有上限，开学季课业重时排班不稳定。",
      "预留应急金：押金、家具、教材、体检或补考都可能突发。",
      "做表：每月固定支出 + 开学月一次性支出。提交咨询时可带上你的预算表，方便对照各校公开学费做短名单。",
    ],
    bodyEn: [
      "Budget in five buckets: tuition, rent, food, transport/phone and insurance/misc. Estimate by actual programme months and level—not a vague “annual living cost” number—and list material/enrolment fees separately.",
      "Rent is the big swing factor: AIS, ICL, Yoobee, NZSE and Future Skills are mostly Auckland-based, so room costs can dominate. Compare tuition gaps together with rent.",
      "Do not build a plan that depends on work income—hours are capped and rosters shrink in heavy study weeks.",
      "Keep a buffer for bond, furniture, books, medical visits or resits.",
      "Make a simple sheet: monthly fixed costs + one-off start-up costs. Bring it to a consultation when shortlisting against published school fees.",
    ],
  },
  {
    slug: "seek-trademe-jobs",
    guideId: "career",
    titleZh: "在 Seek 与 Trade Me 找工作：实用建议",
    titleEn: "Finding work on Seek and Trade Me: practical tips",
    excerptZh: "两个平台怎么用、简历怎么写、学生签证工时要注意什么。",
    excerptEn:
      "How to use both platforms, write a local CV, and mind student work-hour rules.",
    image: "/images/career-feature.png",
    imageAltZh: "奥克兰城市天际线",
    imageAltEn: "The Auckland city skyline",
    bodyZh: [
      "在新西兰找兼职或全职，最常用的是 Seek 和 Trade Me Jobs。两者都能找到零售、餐饮、客服、仓库、行政等入门岗；专业岗和毕业生项目更常出现在 Seek 与 LinkedIn。",
      "Seek：岗位量大、筛选细。建议用关键词（如 barista、retail assistant、customer service）+ 城市/区域搜索，打开 Email alerts，每天看一次新发布。点进职位后先读 Requirements，再决定是否投——比海投更有效。",
      "Trade Me Jobs：本地感强，很多中小商家会发。适合找附近的兼职、临时班、服务类工作。页面信息有时更短，投递前把问题准备好（排班、时薪、是否需要交通）。",
      "简历建议：一页即可，英文为主，结果导向。用动词开头写经历，能量化就量化（例如服务多少顾客、负责什么班次）。不必放照片；联系方式写清手机、邮箱与所在城市。",
      "Cover letter 不必很长：三五段说清你是谁、为什么匹配这个岗、你能马上贡献什么。把职位描述里的关键词自然写进去，系统筛选和招聘官都会更好读。",
      "学生签证工时：请以 Immigration New Zealand 最新规定为准。接班前先确认自己的条件，避免超工时。第一份工可以不完美，重点是准时、沟通清楚、能拿到本地推荐。",
      "面试常见行为问题：团队合作冲突、赶 deadline、一次失败经历。用 STAR（情境—任务—行动—结果）准备两个真实例子就够，别背稿。",
      "投递节奏建议：每周固定投 8–15 个匹配岗，比一天投 50 个更稳。每次面试后记反馈，下一封申请会更准。若你需要简历结构或选岗方向的一对一建议，可以提交咨询申请。",
    ],
    bodyEn: [
      "For part-time or full-time work in New Zealand, Seek and Trade Me Jobs are the two boards most people start with. Both list retail, hospitality, customer service, warehouse and admin roles; professional and graduate roles show up more on Seek and LinkedIn.",
      "Seek: larger volume and finer filters. Search by keyword (barista, retail assistant, customer service) plus city/suburb, set alerts, and check daily. Read the requirements before you apply—targeted applications beat mass sending.",
      "Trade Me Jobs: feels more local, with many small employers. Useful for nearby part-time, casual and service roles. Listings can be short, so prepare questions about roster, pay and transport.",
      "CV tips: keep it to one page, English-first, outcome-focused. Start bullets with verbs and add numbers where you can. No photo needed. Include mobile, email and city.",
      "Cover letters can be short: who you are, why you fit, what you can contribute quickly. Mirror a few keywords from the job ad so both ATS screens and humans can follow.",
      "Student work hours: always check the current Immigration NZ rules before accepting a roster. Your first job does not need to be perfect—reliability and clear communication matter most for local references.",
      "Interviews often use behavioural questions: teamwork conflict, deadline pressure, a failure. Prepare two real STAR examples; do not recite a script.",
      "A steady pace works better than spam: 8–15 matched applications a week, then notes after each interview. If you want help structuring a CV or choosing roles, use the consultation form.",
    ],
  },
  {
    slug: "nz-cv-cover-letter",
    guideId: "career",
    titleZh: "新西兰简历与 Cover Letter 怎么写",
    titleEn: "How to write an NZ CV and cover letter",
    excerptZh: "一页简历、结果导向、关键词对齐职位——比华丽模板更重要。",
    excerptEn:
      "One page, outcomes and keyword fit beat fancy templates.",
    image: "/images/career-feature.png",
    imageAltZh: "奥克兰城市天际线",
    imageAltEn: "The Auckland city skyline",
    bodyZh: [
      "本地简历通常一页：联系方式、教育、经历、技能。不必放照片、年龄、婚姻状况。",
      "经历用动词开头 + 结果：Serving 80+ customers per shift / Managed weekend roster。空泛形容词少写。",
      "针对每个岗位微调：把广告里的关键词（cash handling、customer service、Excel）自然放进经历与技能。",
      "Cover letter：自我介绍、匹配点、可立即贡献的能力，三段左右即可，避免重复简历全文。",
      "文件命名：Firstname_Lastname_CV.pdf。投递前让同学或顾问快速检查错别字与联系方式。",
    ],
    bodyEn: [
      "NZ CVs are usually one page: contact, education, experience, skills. No photo, age or marital status.",
      "Use verb + outcome bullets: “Served 80+ customers per shift.” Cut fluffy adjectives.",
      "Tune each application: mirror role keywords (cash handling, customer service, Excel) in experience and skills.",
      "Cover letter: who you are, why you fit, what you can contribute—about three short paragraphs, not a CV reprint.",
      "Name files clearly (Firstname_Lastname_CV.pdf) and spell-check contacts before you send.",
    ],
  },
  {
    slug: "interview-star",
    guideId: "career",
    titleZh: "本地面试：用 STAR 讲清楚经历",
    titleEn: "NZ interviews: tell your story with STAR",
    excerptZh: "行为面试常见，准备两个真实例子比背稿更管用。",
    excerptEn:
      "Behavioural interviews are common—two real examples beat memorised scripts.",
    image: "/images/career-feature.png",
    imageAltZh: "奥克兰城市天际线",
    imageAltEn: "The Auckland city skyline",
    bodyZh: [
      "常见问题：冲突怎么处理、压力大怎么做、一次失败学到什么、为什么想做这份工。",
      "STAR：情境 Situation、任务 Task、行动 Action、结果 Result。每个例子 1–2 分钟讲完。",
      "英文表达卡壳时，先答结论再补细节，比长时间沉默好。可以礼貌请对方重复问题。",
      "面试当天：提前到、着装干净整洁、带纸质简历。结束后简短感谢即可。",
      "没拿到也记录反馈：是经验、英语还是排班不匹配。下一封申请会更准。",
    ],
    bodyEn: [
      "Common themes: conflict, pressure, failure lessons and why this role.",
      "STAR: Situation, Task, Action, Result—keep each story to 1–2 minutes.",
      "If English stalls, lead with the outcome then add detail; ask to repeat the question if needed.",
      "On the day: arrive early, dress tidy, bring a paper CV. A short thank-you is enough afterwards.",
      "No offer still helps—note whether the gap was experience, English or roster fit.",
    ],
  },
  {
    slug: "ird-work-hours",
    guideId: "career",
    titleZh: "IRD 税号与学生工时合规",
    titleEn: "IRD number and lawful student work hours",
    excerptZh: "先确认签证工时，再申请 IRD；发薪与报税才走得通。",
    excerptEn:
      "Confirm visa hours first, then get an IRD number for payroll and tax.",
    image: "/images/career-feature.png",
    imageAltZh: "奥克兰城市天际线",
    imageAltEn: "The Auckland city skyline",
    bodyZh: [
      "学生能否打工、每周几小时，以签证条件与 Immigration NZ 最新规定为准。接班前自己核对，不要只听同事说。",
      "IRD 税号：有工作后尽快申请，方便雇主发薪与正确扣税。信息填错会导致发薪延误。",
      "拿到雇合约/录用邮件后确认时薪、排班、是否试用期。加班与公共假日规则按劳动法规与合同。",
      "留存每期工资单。换工作时更新银行与税务信息。",
      "不确定签证条款时，先查移民局说明或咨询持牌移民顾问——合规比多上一两个班更重要。",
    ],
    bodyEn: [
      "Whether you can work and how many hours depends on your visa and current Immigration NZ rules—verify before accepting a roster.",
      "Apply for an IRD number promptly so employers can pay you and deduct tax correctly. Wrong details delay pay.",
      "Check pay rate, roster and trial terms in the offer. Overtime and public holidays follow law and your agreement.",
      "Keep payslips and update bank/tax details when you change jobs.",
      "If visa terms are unclear, check Immigration NZ or a licensed adviser—compliance beats extra shifts.",
    ],
  },
  {
    slug: "nz-monthly-budget",
    guideId: "life",
    titleZh: "留学生一个月生活费怎么算",
    titleEn: "A practical one-month NZ living budget",
    excerptZh:
      "房租、饮食、日用品再加交通手机水电网——给奥克兰与其他城市各算一笔约数。",
    excerptEn:
      "Rent, food, daily needs, plus transport, phone and bills—sample Auckland and cheaper-city totals.",
    image: "/images/hero-coast.png",
    imageAltZh: "新西兰海岸与城市生活",
    imageAltEn: "New Zealand coast and everyday life",
    bodyZh: [
      "以下为约 2025–2026 年留学生常见区间（纽币 NZD），以奥克兰为主、其他城市往往更低；实际以当地房租广告与账单为准，入学前请再核一遍。学费、保险、签证费另算，不计入本月生活费。",
      "房租（通常最大头）：奥克兰合租单间大约 NZ$220–350/周（约 NZ$950–1,500/月）；studio / 一居室约 NZ$400–550+/周（约 NZ$1,700–2,400+/月）。惠灵顿、基督城、汉密尔顿等合租单间常可低一截，约 NZ$180–280/周（约 NZ$780–1,200/月），偏远或学生城有时更省。看房时问清电费、网费、水费是否另计。",
      "饮食：自己做饭买菜大约 NZ$350–500/月；偶尔外卖/外食可按 NZ$400–650/月估。日用品（洗护、洗衣、纸巾清洁等）约 NZ$40–80/月。开学月若新买锅具床品，另留一次性预算。",
      "必算的杂项：公交约 NZ$80–150/月（奥克兰 AT HOP，路程与是否有学生优惠差很大）；手机预付/套餐约 NZ$20–40；合租水电分摊约 NZ$40–80；宽带分摊约 NZ$20–40。有车再另加油费与停车，本表按公交学生估算。",
      "样本合计（合租、奥克兰）：节俭档大约 NZ$1,600–1,900/月；适中档大约 NZ$2,000–2,400/月。其他城市合租节俭档常见约 NZ$1,300–1,800。按粗略汇率 1 NZD ≈ 4.2–4.4 CNY，奥克兰节俭档大约 ¥6,700–8,400，适中档大约 ¥8,400–10,600（仅供参考，以银行实时牌价为准）。独居 studio 再往上加房租差即可。",
    ],
    bodyEn: [
      "Figures below are approximate 2025–2026 student ranges in NZD, centred on Auckland (other cities are often cheaper). Verify against local listings and your own bills; tuition, insurance and visa fees are separate.",
      "Rent (usually the biggest line): Auckland shared room about NZ$220–350/week (≈ NZ$950–1,500/month); studio/one-bed about NZ$400–550+/week (≈ NZ$1,700–2,400+/month). In Wellington, Christchurch, Hamilton and similar cities, shared rooms often land around NZ$180–280/week (≈ NZ$780–1,200/month)—sometimes less in smaller student towns. Confirm whether power, internet and water are extra.",
      "Food: groceries if you cook most meals ≈ NZ$350–500/month; with occasional takeaways/eating out budget ≈ NZ$400–650. Daily necessities (toiletries, laundry, household basics) ≈ NZ$40–80. Keep a one-off buffer in month one for pots, bedding and similar start-up buys.",
      "Typical extras students forget: public transport ≈ NZ$80–150 (Auckland AT HOP varies by commute and any student concession); phone prepaid/plan ≈ NZ$20–40; shared utilities ≈ NZ$40–80; shared broadband ≈ NZ$20–40. Car owners add fuel and parking—this sample assumes buses/trains.",
      "Sample monthly totals (shared flat, Auckland): thrifty ≈ NZ$1,600–1,900; mid ≈ NZ$2,000–2,400. In cheaper cities, a thrifty shared lifestyle often sits around NZ$1,300–1,800. Rough CNY note at 1 NZD ≈ 4.2–4.4 CNY: Auckland thrifty ≈ ¥6,700–8,400; mid ≈ ¥8,400–10,600 (check your bank’s live rate). Add the rent gap if you take a studio alone.",
    ],
  },
  {
    slug: "renting-guide",
    guideId: "life",
    titleZh: "新西兰租房：Trade Me 与合租注意点",
    titleEn: "Renting in NZ: Trade Me and flatmate tips",
    excerptZh: "看房要快、材料备齐；押金收据与租约条款必须看清。",
    excerptEn:
      "Move fast with documents ready; read bond receipts and lease terms carefully.",
    image: "/images/hero-coast.png",
    imageAltZh: "新西兰海岸与城市生活",
    imageAltEn: "New Zealand coast and everyday life",
    bodyZh: [
      "整租与独立房间多见 Trade Me Property；找室友常用 Flatmates。奥克兰竞争激烈，回复要快。",
      "看房带上：护照/签证页、录取或在读证明、收入/存款说明、推荐信（如有）。",
      "重点检查：租约时长、押金（bond）收据、暖气与潮气、通勤时间、账单是否另计（电、网、水）。",
      "合租前谈清清洁与客人规则，避免口头约定事后扯皮。",
      "付押金与房租走可追溯方式，保留转账记录。有纠纷可了解 Tenancy Services 指引。",
    ],
    bodyEn: [
      "Trade Me Property is the main listings board; Flatmates is common for shared rooms. Auckland moves fast—reply quickly.",
      "Bring passport/visa evidence, enrolment proof, funds evidence and references if you have them.",
      "Check lease length, bond receipt, heating/damp, commute and whether power/internet/water are extra.",
      "Agree cleaning and guest rules before you move into a flat.",
      "Pay bond/rent through traceable channels and keep records. Tenancy Services guidance helps if issues arise.",
    ],
  },
  {
    slug: "bank-account-setup",
    guideId: "life",
    titleZh: "银行卡办理：四大行开户要点",
    titleEn: "Opening a bank account: the main banks",
    excerptZh: "护照、签证、地址与学生证明——预约国际学生开户更省事。",
    excerptEn:
      "Passport, visa, address and student proof—book an international-student appointment.",
    image: "/images/hero-coast.png",
    imageAltZh: "新西兰海岸与城市生活",
    imageAltEn: "New Zealand coast and everyday life",
    bodyZh: [
      "常见选择：ANZ、ASB、Westpac、BNZ。国际学生通常需要护照、签证/入境证明、地址证明与学生证明。",
      "落地前可预约国际学生开户；部分银行支持预开户，落地后再激活卡片。",
      "问清：账户月费、境外汇款费用、借记卡与网银激活方式。",
      "有 IRD 后打工发薪更顺。不要把验证码或网银密码告诉任何人。",
      "开好户再处理房租自动扣款与手机套餐，减少现金与多平台转账麻烦。",
    ],
    bodyEn: [
      "Common banks: ANZ, ASB, Westpac, BNZ. Students usually need passport, visa/entry evidence, address proof and student confirmation.",
      "Book an international-student appointment; some banks allow pre-arrival setup then card activation onshore.",
      "Ask about monthly fees, overseas transfer costs and how to activate cards/online banking.",
      "An IRD number helps payroll later. Never share one-time codes or banking passwords.",
      "With an account ready, rent autopay and phone plans become much simpler.",
    ],
  },
  {
    slug: "supermarket-savings",
    guideId: "life",
    titleZh: "超市特价与省钱买菜",
    titleEn: "Supermarket specials and saving on groceries",
    excerptZh: "Pak'nSave、Countdown、New World 怎么搭配买更省。",
    excerptEn:
      "How to combine Pak'nSave, Countdown and New World without overspending.",
    image: "/images/hero-coast.png",
    imageAltZh: "新西兰海岸与城市生活",
    imageAltEn: "New Zealand coast and everyday life",
    bodyZh: [
      "三大连锁：Countdown（Woolworths）、New World、Pak'nSave。整体价格 Pak'nSave 常更低，适合一周采购。",
      "每周看 App/传单特价，按特价做菜单比冲动买肉菜更省。",
      "办积分卡（如 Onecard 等）留意会员价；亚洲超市补米面调料与家乡味道。",
      "冷冻与批量：面包、肉类可分装冷冻；临期折扣区适合当天吃的菜品。",
      "开学季先备基础调料与早餐物资，减少天天小额外卖。",
    ],
    bodyEn: [
      "The big three are Countdown (Woolworths), New World and Pak'nSave. Pak'nSave is often cheapest for a weekly shop.",
      "Plan meals around weekly specials in the apps/flyers instead of impulse buys.",
      "Use loyalty cards for member pricing; Asian grocers fill pantry gaps from home.",
      "Freeze and portion meat/bread; use markdown shelves for same-day meals.",
      "Stock basics in week one so you rely less on takeaways.",
    ],
  },
  {
    slug: "phone-sim-transport",
    guideId: "life",
    titleZh: "手机卡与公交怎么开通",
    titleEn: "Getting a SIM and using public transport",
    excerptZh: "落地先解决通讯与通勤，找房找工才方便。",
    excerptEn:
      "Sort a SIM and transport early—housing and jobs get easier after that.",
    image: "/images/hero-coast.png",
    imageAltZh: "新西兰海岸与城市生活",
    imageAltEn: "New Zealand coast and everyday life",
    bodyZh: [
      "常见运营商：Spark、One NZ、2degrees 等。机场或市区门店可办预付费套餐，带护照即可。",
      "选套餐看通话与流量是否够用；可先短周期预付费，稳定后再换长期计划。",
      "公交：奥克兰用 AT HOP 等城市卡；其他城市有对应交通卡或付款方式。学生是否有折扣以当地交通局为准。",
      "Google Maps / 当地公交用 App 查实时班次。夜间与周末班次可能变少。",
      "重要账号开启双因素时，确保你能接收短信或改用验证器 App。",
    ],
    bodyEn: [
      "Common carriers include Spark, One NZ and 2degrees. Prepaid SIMs are available at airport/city stores with your passport.",
      "Start with a short prepaid plan; switch later when usage is clear.",
      "Auckland uses AT HOP; other cities have their own cards/payments. Student discounts depend on the local authority.",
      "Use Maps and local transit apps; nights and weekends can have fewer services.",
      "When enabling two-factor authentication, confirm SMS access or move to an authenticator app.",
    ],
  },
  {
    slug: "health-insurance-gp",
    guideId: "life",
    titleZh: "保险与看病：GP 怎么挂",
    titleEn: "Insurance and seeing a GP",
    excerptZh: "先搞清保险覆盖，再注册社区 GP；急诊只用于紧急情况。",
    excerptEn:
      "Know your cover, enrol with a GP, and keep ED for emergencies.",
    image: "/images/hero-coast.png",
    imageAltZh: "新西兰海岸与城市生活",
    imageAltEn: "New Zealand coast and everyday life",
    bodyZh: [
      "国际学生通常需要医疗保险。注册学校前确认保险是否符合要求、门诊与处方是否自费较多。",
      "日常生病找社区 GP（全科医生）。可提前注册附近诊所，问清是否接收新患者与预约方式。",
      "急诊部（ED）用于急重症，不是普通感冒的首选，等待时间可能很长。",
      "处方药在药房购买；保留收据以备保险报销（如条款允许）。",
      "心理健康同样重要：学校 counseling 与学生支持服务可主动约，不必硬撑。",
    ],
    bodyEn: [
      "International students usually need medical insurance—confirm it meets school rules and what you still pay for GP visits and prescriptions.",
      "For everyday illness, enrol with a local GP; ask if they take new patients and how booking works.",
      "Emergency departments are for urgent cases, not routine colds—waits can be long.",
      "Collect prescriptions at a pharmacy and keep receipts if your policy reimburses.",
      "Use campus counselling/student support early when stress builds—do not wait until crisis.",
    ],
  },
  {
    slug: "arrival-first-week",
    guideId: "life",
    titleZh: "落地第一周清单",
    titleEn: "Your first-week arrival checklist",
    excerptZh: "住宿、手机、银行、交通、注册——按天推进不容易乱。",
    excerptEn:
      "Housing, SIM, bank, transport, enrolment—day-by-day keeps it calm.",
    image: "/images/hero-coast.png",
    imageAltZh: "新西兰海岸与城市生活",
    imageAltEn: "New Zealand coast and everyday life",
    bodyZh: [
      "第 1–2 天：入住短租/宿舍，买手机卡，确认WIFI与紧急联系人。",
      "第 3–4 天：银行预约/开户，交通卡充值，熟悉超市与通勤路线。",
      "第 5–6 天：学校注册、学生卡、Orientation，加入课程平台（Canvas 等）。",
      "第 7 天：整理文件备份（护照、签证、offer、保险），列出待办（租房长约、IRD、GP）。",
      "身体与时差：前几天别排太满。需要帮助时写国际学生办公室或提交咨询申请。",
    ],
    bodyEn: [
      "Days 1–2: check into short stay/halls, get a SIM, confirm Wi-Fi and emergency contacts.",
      "Days 3–4: bank appointment, top up transport, learn supermarket and commute routes.",
      "Days 5–6: enrolment, student ID, orientation and course platforms (e.g. Canvas).",
      "Day 7: back up passport/visa/offer/insurance files; list next tasks (longer lease, IRD, GP).",
      "Protect sleep and jet lag—do not overbook. Contact international student support or use the consultation form if you get stuck.",
    ],
  },
];

export function getGuide(id) {
  return guides.find((guide) => guide.id === id);
}

export function getArticle(slug) {
  return articles.find((article) => article.slug === slug);
}

export function getArticlesByGuide(guideId) {
  return articles.filter((article) => article.guideId === guideId);
}

export function getHomeArticles(locale) {
  const zh = locale === "zh";
  return guides.map((guide) => {
    const featured = getArticle(guide.featuredSlug);
    return {
      guideId: guide.id,
      title: zh ? guide.titleZh : guide.titleEn,
      summary: zh ? guide.summaryZh : guide.summaryEn,
      featured: zh
        ? guide.featuredTitleZh || featured?.titleZh
        : guide.featuredTitleEn || featured?.titleEn,
      featuredSlug: guide.featuredSlug,
      action: zh ? siteCopy.zh.exploreGuide : siteCopy.en.exploreGuide,
      read: zh ? siteCopy.zh.readArticle : siteCopy.en.readArticle,
      image: guide.image,
      imageAlt: zh ? guide.imageAltZh : guide.imageAltEn,
    };
  });
}
